### ISSUE TITLE
SSH Generators

### ISSUE THREAD

**Issue by Adam0Wasik** [DevToys-app/DevToys#1020]
### What improvement do you think would an existing feature or tool in DevToys?

ssh and other key generators and secure managers, integrations for most used by devs services like GitLab GitHub etc

### Solution/Idea

auth purposes e.g. for GIT usage

### Comments

something like in Kraken or fork

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
