### ISSUE TITLE
Color palettes

### ISSUE THREAD

**Issue by ppo** [DevToys-app/DevToys#1037]
### What feature or new tool do you think should be added to DevToys?

Allow to select the color code of a palette.

### Why do you think this is needed?

- Display color squares and copy color code on click.
- Allow to import/define our own palettes.

### Solution/Idea

Similar to [Material Design Colors](https://materialui.co/colors/).

### Comments

Already mentioned in #212 (closed)

_No response_

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
