### ISSUE TITLE
Add List difference finder

### ISSUE THREAD

**Issue by bvtvusn** [DevToys-app/DevToys#1044]
### What feature or new tool do you think should be added to DevToys?

List difference finder

### Why do you think this is needed?

Useful when having two columns in excel and wondering if they are exactly the same. Solution: Just copy it into a list difference finder! Can actually be used for any text! I use it quite regularly in my daily work.

### Solution/Idea

Two text boxes for input, A and B.
The output gives four lists: "Only in A", "only in B", "in both" and "all combined".
Should have option for doing case insensitive comparison.
Similar to: http://www.listdiff.com/

**Comment by Antjac** [comment]
I could try to do this feature, this would be my first feature and I think it's a good one.

**Comment by Antjac** [comment]
I made it, can I make a PR even it's untriaged ?
