### ISSUE TITLE
sha256 decode\encode

### ISSUE THREAD

**Issue by hasket** [DevToys-app/DevToys#1052]
### What feature or new tool do you think should be added to DevToys?

Hello. Can you add sha256 decoder\encoder for text and files?

### Why do you think this is needed?

I think sha256 more security than base64. This feature is important in my work every day. You'll save my mental health.

**Comment by dineiar** [comment]
Regarding the decoder, sha256 is a (one-way) [hash function](https://en.wikipedia.org/wiki/Hash_function), not an [encoding](https://en.wikipedia.org/wiki/Binary-to-text_encoding) like Base64. Therefore, there is no such thing as a "sha256 decoder".
Various websites try to decrypt a sha256 hash into the input string using very limited rainbow tables. I believe DevToys (core) should not include a tool for decrypting hashes using rainbow tables. Interested developers may include it through extensions.

Regarding the encoder, DevToys already supports sha256 hashing on Generators > Hash / Checksum.

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
