### ISSUE TITLE
Boolean expression simplifier

### ISSUE THREAD

**Issue by TrangOul** [DevToys-app/DevToys#1057]
### What feature or new tool do you think should be added to DevToys?

A Boolean expression calculator which can simplify the given logical expression.

| Capability | Priority |
|---|---|
| Accept a Boolean expression in programming (`&&`, `\|\|`, `!`) or text (`AND`, `OR`, `NOT`) notation. | Must |
| Support NAND and NOR operators (as logically complete). | Should |
| Support operator (`A AND B`) and function (Excel-like) notation (`AND(A, B)`). | |
| Allow longer variable names (`has_access`, `isAdmin`), so it's possible to paste the code directly (and use the same var names in the output). | |
| Output CNF and DNF forms, as well as NAND and NOR (see above). | |
| Generate a truth table with all the variables and the result (2^vars rows). | |
| Support additional notations for operators (such as math: `∧`, `∨`, `¬`/`~`). | Could |
| Support additional notations for Boolean literals (`true`/`false`, `T`/`F`, `1`/`0`, `⊤`/`⊥`) in the truth table. | |
| Output AND+NOT and OR+NOT forms. | |
| Support prefix (Polish) and postfix (reverse Polish) notation. | |
| Draw a Venn diagram (for small numbers of variables - intersecting circles can be used only with up to 3 vars; can be slighly extended with ellipses). | |
| Support additional logical operators (XOR, IMPLIES and so on) - both in input and output (if chosen). | |

### Why do you think this is needed?

Often used by programmers (or actually _not_ used - hence inefficient code and `if`s spanning multiple lines). 

### Solution/Idea

Input:
`(a && b) || (a && c) || (!b && !c)` (programming notation)
`(a AND b) OR (a AND c) OR (NOT b AND NOT c)` (text notation)

Output:
`a || (!b && !c))`
`a OR (NOT b AND NOT c)`

Truth table
| a | b | c | result |
|---|---|---|--------|
| 0 | 0 | 0 |   1    |
| 0 | 0 | 1 |   0    |
| 0 | 1 | 0 |   0    |
| 0 | 1 | 1 |   0    |
| 1 | 0 | 0 |   1    |
| 1 | 0 | 1 |   1    |
| 1 | 1 | 0 |   1    |
| 1 | 1 | 1 |   1    |

Venn diagram:
![image](https://github.com/veler/DevToys/assets/5629046/d87a6794-b9d6-4780-bf23-0d8061415873)

### Comments

Available as an online tool: [Wolfram Alpha](https://www.wolframalpha.com/input?i=%28a+%26%26+b%29+%7C%7C+%28a+%26%26+c%29+%7C%7C+%28%21b+%26%26+%21c%29), [dCode](https://www.dcode.fr/boolean-expressions-calculator) - it'd be handy to have such a tool offline.

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
