### ISSUE TITLE
CSV file joiner (INNER JOIN like in SQL)

### ISSUE THREAD

**Issue by bvtvusn** [DevToys-app/DevToys#1062]
### What feature or new tool do you think should be added to DevToys?

Feature that can join two csv documents on a specific key. For example if both documents have email address as a column, these columns can be used as a key, and the information from both CSV documents will be combined into one row in the output.
Should support INNER JOIN, RIGHT JOIN, LEFT JOIN and FULL JOIN.

### Why do you think this is needed?

This can reduce the workload a lot when dealing with long lists that must be merged.

### Solution/Idea

LOADING DATA:
Two lists must be imported, A and B. User can input data either from files or from clipboard (Pasting from excel is especially important). User must specify if the lists are comma separated or tab separated or something else. User must specify wheter the data is encapsulated in quotes. User must specify if the lists contains a header row.

JOIN OPERATION:
The user should get a preview of the two tables, and should be able to click on the column that he wants to use as the key used in the JOIN operation. If the key column contains duplicate values, the user should get a warning. The user then selects one of the four join types (inner, righ, left, full). and presses "Execute".

EXPORTING DATA:
similar to the loading data section, but in reverse.
Maybe it would be useful with a "delete column" functionality here?

### Comments

Similar to joins in excel power query (but with fewer clicks to get it done)

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
