### ISSUE TITLE
JSON Formatter: move settings to the side and give more space to the formatter

### ISSUE THREAD

**Issue by diplopito** [DevToys-app/DevToys#1082]
### What improvement do you think would an existing feature or tool in DevToys?

JSON Formatter is a very useful tool but... at the moment the configuration settings take space that should be given to the JSON formatter.

### Solution/Idea

JSON Formatter could have a gear icon next to the title to add the 2 settings (Indentation and Sorting) that are taking 25% of the area at the moment. All this space can be given to the formatter. And, since it runs inside the configuration of DevToys, the side bar should be able to be collapsed as well.

**Comment by veler** [comment]
Hi,
In DevToys 2.0 (which is coming in a few months), there will be a Compact Spacing option to make all these settings smaller. Would that be enough?
![image](https://github.com/DevToys-app/DevToys/assets/3747805/af5e4429-0266-4222-8c8d-c74fcd5d4e6b)
![image](https://github.com/DevToys-app/DevToys/assets/3747805/28ad7fb3-5c55-444c-830c-32e76dd1d6a2)
![image](https://github.com/DevToys-app/DevToys/assets/3747805/bc355ca6-81b6-49ea-a4f3-cad7e2562750)
![image](https://github.com/DevToys-app/DevToys/assets/3747805/427939ac-d82d-493f-b7a0-17eeaef9ea9c)

Alternatively, I agree with a gear icon, but it's not the most discoverable and this approach might not work well with every tools.

**Comment by diplopito** [comment]
Thanks for your reply. Working with Devs you can count on the "universality" of the gear for settings (IMO). Moving the configuration to a common _Settings panel_ could be a good solution as well. The area that the title and the configuration occupy is big. The image enclosed shows the differente between Json Formatter and JSONedit: with the latter the visibility is double (3 vs 7 nodes). It's true that the font size is also smaller (and font-size could be part of the configuration settings too):

![json formatter](https://github.com/DevToys-app/DevToys/assets/26707508/ebab4aa9-0608-4062-ad25-910fa28a8675)

**Comment by veler** [comment]
Again, I agree in overall, it takes much space. Perhaps it's something we will consider in the future, but it's likely too late to add it in last minute in DevToys 2.0.

For collapsing/expanding nodes, that's something you can already do by passing the mice cursor on the margin of the editor.
![image](https://github.com/DevToys-app/DevToys/assets/3747805/30028531-eb69-4e55-8b35-ba80b49fc020)

This won't be something we can control, as the editor is a third party library: https://microsoft.github.io/monaco-editor/
