### ISSUE TITLE
hexadecimal decode\encode

### ISSUE THREAD

**Issue by Vikec** [DevToys-app/DevToys#1083]
### What feature or new tool do you think should be added to DevToys?

Hello Can you add a text conversion hexadecimal feature?

### Why do you think this is needed?

I think it's used a lot

### Solution/Idea

like hackbar

**Comment by vishva-karma** [comment]
@Vikec I appreciate your idea for the new feature. To get quick feedback, please extend the description with some examples in the `Solution/Idea` section.
