### ISSUE TITLE
时间戳支持毫秒、微秒、纳秒

### ISSUE THREAD

**Issue by sinceHYJ** [DevToys-app/DevToys#1089]
### What feature or new tool do you think should be added to DevToys?

时间戳转换工具中，目前只能支持秒级时间戳，希望支持不同单位毫秒、微秒、纳秒等

### Why do you think this is needed?

日常开发中，逻辑中经常使用毫秒的时间戳

**Comment by veler** [comment]
Hi,
Thanks for the suggestion. We already support Seconds and Milliseconds in DevToys 2.0, which will be release later this spring.
