### ISSUE TITLE
AVRO Schema from JSON & JOLT Transform

### ISSUE THREAD

**Issue by BrunOshiro** [DevToys-app/DevToys#1090]
### What improvement do you think would an existing feature or tool in DevToys?

I love this tool. It's so useful in my daily routine.

There are just 3 items that will make me don't use site tools anymore and use only DevToys:

1. Json Path Evaluate
2. AVRO Schema from JSON
3. JOLT Transform

### Solution/Idea

1. Json Path Evaluate - https://jsonpath.com/
2. AVRO Schema from JSON - https://converts.me/tools/generation/metadata/avro-schema-from-json
3. JOLT Transform - https://jolt-demo.appspot.com/#modify-typeConversion

### Comments

You created a great tool. Thank you very much!

**Comment by veler** [comment]
Hi,
Thanks for the suggestion. JSON Path tester has already been added to DevToys 2.0, which will be released later this spring.

**Comment by veler** [comment]
Hi,
JSON Path tester is now available. For the others, these are good ideas for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
