### ISSUE TITLE
Portable Version needed

### ISSUE THREAD

**Issue by Takenforgranted** [DevToys-app/DevToys#1098]
### What feature or new tool do you think should be added to DevToys?

Hoping that I can get  the portable version (as a .zip or .rar) instead of the only appinstaller.

### Why do you think this is needed?

I think it can make the software much easier to launch and more convenient to use it anywhere.

**Comment by veler** [comment]
Duplicate with #514.
This is a supported scenario in DevToys 2.0, to be released this spring.
