### ISSUE TITLE
curl to python requests code

### ISSUE THREAD

**Issue by starSgz** [DevToys-app/DevToys#1103]
### What feature or new tool do you think should be added to DevToys?

I love this tool.  I often use this website “https://spidertools.cn/#/formatJSON”. It is similar this tool. The website 's  "curl转requests"  function is very good . But this is an online website, so it will push my data onto the Internet.  I don't like it .

### Why do you think this is needed?

improve function

**Comment by starSgz** [comment]
maybe you can add java request or other language to help other coders , thanks

**Comment by marlkiller** [comment]
https://curlconverter.com/python/

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
