### ISSUE TITLE
load error:DevToys.Api.GUI.MultilineTextInput 

### ISSUE THREAD

**Issue by niyari** [DevToys-app/DevToys#1104]
### Current behavior

Commit 18912b8a338a12c34ee5071a237bc95d5ad8902e does not start the tool.

### Expected behavior

Each tool starts.

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/2970321/3dc9feff-baec-4009-bee1-2755f364fbba)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0.0-pre.0

**Comment by veler** [comment]
Hello,
We just shipped a breaking change 2 days ago. Please pull the latest commit on `main` branch of `DevToys` and `DevToys.Tools` repositories and retry.

**Comment by veler** [comment]
See https://github.com/DevToys-app/DevToys/pull/1102
And https://github.com/DevToys-app/DevToys.Tools/commit/62ca83c5b5f05917d310da77fc1f8d3b3e89bcff
