### ISSUE TITLE
JSON To YAML Convert should preserve unicode escape

### ISSUE THREAD

**Issue by latop2604** [DevToys-app/DevToys#1112]
### Current behavior

When converting a json document containing unicode sequence escape, the caracter is replace in the output.

### How to reproduce it (as minimally and precisely as possible)

Having `{ "Name": "Dor\u00e9" }` become `Name: Doré`

### Expected behavior

It should be `Name: "Dor\u00e9"`

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/2058133/45a2ab8b-a069-4510-9c51-d7a20846125c)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

**Comment by sasakirione** [comment]
started working on it!
https://github.com/sasakirione/DevToys.Tools/tree/fix_jsonyaml_unicode_escape
