### ISSUE TITLE
Missing letter in PasswordGenerator's UppercaseDescription 

### ISSUE THREAD

**Issue by Danteclave** [DevToys-app/DevToys#1120]
### Current behavior

Very small issue: in PasswordGenerator.resx, english version: UppercaseDescription is missing an I
What actually is written
Use uppercase characters (ABCDEFGHJKLMNOPQRSTUVWXYZ)

### Expected behavior

It should be "Use uppercase characters (ABCDEFGHIJKLMNOPQRSTUVWXYZ)"

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

**Comment by veler** [comment]
Fixed in https://github.com/DevToys-app/DevToys.Tools/commit/c53d68104cbe7490187ed445b5a541984813fc3b
