### ISSUE TITLE
Token counter for generative AI

### ISSUE THREAD

**Issue by Zaffer** [DevToys-app/DevToys#1122]
### What feature or new tool do you think should be added to DevToys?

Token counter for text that counts the token for LLM's like ChatGPT etc. Similiar to TikToken or whatever OpenAI's formula is.

### Why do you think this is needed?

Quickly count tokens in the app.

### Solution/Idea

Implement the opensource algo for counting these tokens.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
