### ISSUE TITLE
Chmod!

### ISSUE THREAD

**Issue by waffle-frame** [DevToys-app/DevToys#1126]
### What feature or new tool do you think should be added to DevToys?

`chmod` allows you to control access rights to files and directories on UNIX-like operating systems

### Why do you think this is needed?

Including `chmod` in a universal tool will make it more complete and functional. This will add another useful feature for developers

### Solution/Idea

https://github.com/Mayowa-Ojo/chmod-cli

**Comment by veler** [comment]
@phiali started working on it some time ago! https://github.com/phiali/DevToys/tree/chmod-calculator

![image](https://github.com/DevToys-app/DevToys/assets/3747805/a37efa79-f917-4dd2-be74-90cbfb387221)

**Comment by waffle-frame** [comment]
> @phiali started working on it some time ago! https://github.com/phiali/DevToys/tree/chmod-calculator
> 

Great job @phiali! 
If you have time and desire to make it a little more functional, study the material with [sticky bit](https://docs.oracle.com/cd/E19683-01/806-4078/6jd6cjs34/index.html).

**Comment by phiali** [comment]
Thanks! It was all very bare-bones and most definitely work-in-progress. I wasn't going to look at it again until after DevToys 2.0 came out. I had quite a trying time of code iterations taking 30 to 40 seconds to show up which made debugging a nightmare. Due to architectural changes in DevToys 2.0 this should apparently be a lot better.

But if anyone else would like to use the code as a basis for something now then please do go ahead 🙂

**Comment by Antjac** [comment]
I think I can do it to port to DevToys 2.0, it seems to be quite easy

**Comment by veler** [comment]
> I think I can do it to port to DevToys 2.0, it seems to be quite easy

Sure thing. With pleasure!
Also, how about giving this the opportunity to test our documentation and SDK again?

Tools in DevToys 2.0 are now extensions. You can make your own tools and publish them under your own name. Here is how (this documentation is complete, but not published on a dedicated website yet):

1. Setup your dev environment:  https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/getting-started/setup.md
2. Create an extension project: https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/getting-started/create-an-extension.md
3. Build and debug: https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/getting-started/debug-an-extension.md
    a. How to make a UI: https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/guidelines/UX/basic-input/button.md
    b. How to make a CLI tool:  https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/guidelines/command-line-tool.md
5. Publish it: https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/getting-started/publish.md


Finally, to read this documentation in a more pleasant way, I can suggest you to clone the Documentation repository and follow the Setup and Run Locally instructions here: https://github.com/DevToys-app/Documentation/blob/main/README.md

**Comment by Antjac** [comment]
Thx @veler, concerning the location, don't you think the best one is "Encoder/Decoder" than "Convert" ?

**Comment by veler** [comment]
I agree! It would fit better.

**Comment by dineiar** [comment]
Hello @veler! First of all, thanks for your work. I am eagerly waiting for DevToys 2.0 release!

I've just cloned the repositories of DevToys and DevToys.Tools and built them on a Mac (arm64) using VS Code following the documentation you linked here. It worked mostly fine (I was able to run the GUI and use the tools). However, I would like to point out a few things:

1. I had to change the `program` attribute of the "DevToys MacOS arm64" entry in `launch.json` to:
```"program": "${workspaceFolder}/bin/Debug/AnyCPU/DevToys.MacOS/net8.0-macos/osx-arm64/DevToys.app/Contents/MacOS/DevToys",```
The original path had a few extra `.MacOS` in a few places. I was about to commit this change and open a PR, but I'm not sure if this path is obsolete or if I have some local configuration that generates the app in a diferent path for some reason, so I'm just reporting it here. The "DevToys MacOS x64" entry probably has the same situation, but I didn't test it.

2. The first part in the documentation for "build and debug" an extension (https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/getting-started/debug-an-extension.md), under the title "One-time configuration", involves creating a Properties folder and a `launchSettings.json` file, but do not mention what IDE is this focused on. I thought that `launchSettings.json` was only used by Visual Studio, but to be honest I didn't test it on VSCode to check (I built the Tools project using the `build.sh` script and invoked the GUI directly using the command line with exported variables to load the extension). So, just to confirm: is this Properties/launchSettings.json file applicable to VSCode and JetBrains Rider as well?

I'm sorry for extending this discussion in this unrelated issue, I just wanted to reply to your [previous comment here](https://github.com/DevToys-app/DevToys/issues/1126#issuecomment-2077432628).

**Comment by veler** [comment]
Hi @dineiar 

> 1. The original path had a few extra `.MacOS` in a few places.

Great catch! These are obsolete path and need to be updated. Feel free to open a PR for it 😁

> is this Properties/launchSettings.json file applicable to VSCode and JetBrains Rider as well?
Yes! It applies to VS, VS Code and Rider.

**Comment by veler** [comment]
This tool be made as an extension using our SDK: https://devtoys.app/doc
Anyone wants to try?

**Comment by veler** [comment]
Hi,
This is still a good idea for an [extension](https://devtoys.app/doc). I'd suggest anyone willing to continue it to extract the code from https://github.com/phiali/DevToys/tree/chmod-calculator and create an extension following the documentation.
Thanks
