### ISSUE TITLE
Spanish translation issue

### ISSUE THREAD

**Issue by abelardo-casadelascarcasas** [DevToys-app/DevToys#1132]
### What improvement do you think would an existing feature or tool in DevToys?

At the below picture:
![image](https://github.com/DevToys-app/DevToys/assets/165779367/1489b176-e808-4706-8c20-789d75f10f7a)
you can read "Envolver palabra".

### Solution/Idea

This is an example of bad translation into Spanish.

The correct translation is "Ajuste de línea".

**Comment by veler** [comment]
Hello,
Thanks for the feedback. Is this issue in DevToys 1.0 or 2.0?
Thanks

**Comment by abelardo-casadelascarcasas** [comment]
![image](https://github.com/DevToys-app/DevToys/assets/165779367/62bcd53d-bfc6-458e-90b2-f38ad836ff33)

**Comment by veler** [comment]
Thanks! We're not updating DevToys 1.0 anymore. But it looks like it's correctly translated in 2.0: 
![image](https://github.com/DevToys-app/DevToys/assets/3747805/a96d2c98-0875-45a0-8e17-7027f889bda5)

https://crowdin.com/editor/devtoys/878/en-es?view=comfortable&filter=basic&value=5

**Comment by abelardo-casadelascarcasas** [comment]
I downloaded this app from Windows Store.

**Comment by veler** [comment]
Oh DevToys 2.0 isn't released yet 😅

**Comment by abelardo-casadelascarcasas** [comment]
Hi there!

When is it planned to be released?

Brs.

**Comment by veler** [comment]
We're hoping in June
