### ISSUE TITLE
No tool displayed

### ISSUE THREAD

**Issue by Antjac** [DevToys-app/DevToys#1133]
### Current behavior

Hi,

I've just pulled the last main branch. When I run it, I don't see any tool :-(
I've re-run init.ps1 script but no change.

Did I miss something ?

### How to reproduce it (as minimally and precisely as possible)

Just pull the main branch and run it

### Expected behavior

Get the list of tools

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/13543730/5df13bff-0305-4e6b-a052-bf151a5237d9)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0

**Comment by veler** [comment]
Hello,

That's normal, we moved the tools to a different repository: https://github.com/DevToys-app/DevToys.Tools

To deploy it in DevToys:

1. Follow instructions in this page: https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/getting-started/setup.md
2. Then open the DevToys.Tools solution in Visual Studio, and press F5.
