### ISSUE TITLE
Localize groups of tools.

### ISSUE THREAD

**Issue by niyari** [DevToys-app/DevToys#1135]
### What feature or new tool do you think should be added to DevToys?

I want to translate categories so that I can select tools intuitively.

### Why do you think this is needed?

This file is not recognized by Crowdin and is therefore hidden from the translator.
`src/app/dev/DevToys.Blazor/BuiltInGroups/Groups.resx`

### Solution/Idea

Change Crowdin configuration or add file path to crowdin.yml

### Comments

![image](https://github.com/DevToys-app/DevToys/assets/2970321/1ad7b884-c5ca-4637-b220-214917ab54df)

**Comment by veler** [comment]
Hello,
These groups are defined in DevToys.Tools repository.
They're also included in Crowdin. Here is the one for Converters, for example : 

https://crowdin.com/editor/devtoys/1004/en-ja?view=comfortable

**Comment by niyari** [comment]
That is correct!
So this was affected by the recent project separation.
This was not a feature request, but a fix.
