### ISSUE TITLE
Add Support for WebP Format in Image Conversion Tool

### ISSUE THREAD

**Issue by hjxhjxjx** [DevToys-app/DevToys#1136]
### What improvement do you think would an existing feature or tool in DevToys?

The conversion of WebP images to JPG format.

### Solution/Idea

I would like to request the addition of WebP format support in the “Image Format Conversion Tool” within DevToys. 
Thank you for considering this request.

**Comment by veler** [comment]
This is done in DevToys 2.0, which will be released soon.
