### ISSUE TITLE
URL shortener

### ISSUE THREAD

**Issue by ChrisBelwinds** [DevToys-app/DevToys#1137]
### What improvement do you think would an existing feature or tool in DevToys?

Couldn‘t you add a URL shortener to your great DevToys.app for Mac? 

### Solution/Idea

A free webservice could be utilized, if the feature could not be implemented locally. 

### Comments

Thanks in advance.

**Comment by btiteux** [comment]
Hello, 
I'm not sure it's possible to create a URL shortener without using third-party services if you want to share the link.

We need more information about how we want the tool to behave if it's to be used locally.
- Would you like to store the link and display them?
- Be able to edit an existing link?
- ...
 
If you want to share the generated link, in this case, we need to "choose" or let the user choose which provider he wants to use to create the link. 

Do we want to support paid third-party services?

**Comment by veler** [comment]
Anything online is out of scope for the base DevToys app. A URL shortener could be good third-party extension idea though.

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
