### ISSUE TITLE
Hex viewer/editor

### ISSUE THREAD

**Issue by kmistrytnp** [DevToys-app/DevToys#1145]
### What feature or new tool do you think should be added to DevToys?

A hex viewer/editor would be a nice addition

### Why do you think this is needed?

Sometimes a file is not "working correctly" for some reason so a tool to check for non-ascii characters would be useful

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
