### ISSUE TITLE
Web tools: DNS lookup

### ISSUE THREAD

**Issue by XVII** [DevToys-app/DevToys#1151]
### What feature or new tool do you think should be added to DevToys?

A simple DNS lookup would be nice.

### Why do you think this is needed?

Covers a new category of web-oriented dev tools.

### Solution/Idea

Similar to existing online toolbox websites like https://toolbox.googleapps.com/apps/dig/

### Comments

Doesn't need to be dig specifically, but some basic DNS lookup functionality is useful.

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
