### ISSUE TITLE
SAML Decoder / Encoder

### ISSUE THREAD

**Issue by XVII** [DevToys-app/DevToys#1152]
### What feature or new tool do you think should be added to DevToys?

A SAML Encoder/Decoder similar to https://toolbox.googleapps.com/apps/encode_decode/

### Why do you think this is needed?

Similar use case to URL & Base64 Decoders ,etc.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
