### ISSUE TITLE
JWT Decoder timestamp UI on hover

### ISSUE THREAD

**Issue by MrCodeWeaver** [DevToys-app/DevToys#1155]
### What feature or new tool do you think should be added to DevToys?

When decoding a JWT if there is a timestamp such as `"exp": 1715097085,` then it would be nice to have that when hovering over the timestamp it would show a tooltip with the datetime in human readable format. Ideally converted the whatever timezone the PC timezone is using.

### Why do you think this is needed?

I often want to know when a JWT expires. and end up having to google to get from a timestamp into a human readable form. Or I just end up using https://jwt.io/ which has this feature.

### Solution/Idea

![image](https://github.com/DevToys-app/DevToys/assets/12052413/b1938385-6cdf-474f-942c-ea55d8173bfb)

**Comment by veler** [comment]
Hello,
This has been added to DevToys 2.0, which will be released in a few weeks
