### ISSUE TITLE
ObjectId generator

### ISSUE THREAD

**Issue by Skyppid** [DevToys-app/DevToys#1163]
### What feature or new tool do you think should be added to DevToys?

As someone working a lot with MongoDB it would be beneficial to be able to generate ObjectIds.

### Why do you think this is needed?

A tool to generate ObjectIds like the UUID generator. Alternatively add it to that one :)

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
