### ISSUE TITLE
Text comparison lag/crash

### ISSUE THREAD

**Issue by ExPikaPaka** [DevToys-app/DevToys#1164]
### Current behavior

When I copy text from field 'Old text' 'New text' s via 'CTRL + C' program lags for like 10-30 seconds or crash

### How to reproduce it (as minimally and precisely as possible)

1. Open last DevToys release.
2. Goto 'Text' part.
3. Select 'Text comparison'
4. Input some text in any field
5. Select text via 'CTRL + A' or mouse
6. Press 'CTRL + C'

### Expected behavior

Instant copy, no lag.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Версия 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

**Comment by veler** [comment]
Hello,
This got fixed in DevToys 2.0, which will be released in a few weeks.
