### ISSUE TITLE
CSR parser in Encoders/Decoders section

### ISSUE THREAD

**Issue by Erfankam** [DevToys-app/DevToys#1165]
### What feature or new tool do you think should be added to DevToys?

A new decoder can parse CSR(s) and show its fields and attributes. An you know, in order to parse CSR, we need some not such easy working tool like Openssl.

### Why do you think this is needed?

One of popular **cryptography objects** are _certificate signing requests_ (_CSR_). Any developer or tester can use this feature in order to check **CSR fields and validity of its signature**. By the way, this could be useful for any security analyst to check CSR integrity.

### Solution/Idea

Add new entry in Encoders/Decoders sub menu and a UI similar to Certificate section. I am so eager to work on it, by the way.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks

**Comment by Erfankam** [comment]
I disagree with you. As we have certificate parser as an ASN1 object type, we can also have another ASN1 object type parser like CSR!

**Comment by Erfankam** [comment]
Can I work on it?
@veler
