### ISSUE TITLE
Regex Tester - match highlighting wrong when it spans multiple lines

### ISSUE THREAD

**Issue by alexclarkmusa** [DevToys-app/DevToys#1171]
### Current behavior

On the Regex Tester, if you've selected the Singleline option and are testing a Regex that matches some text which spans multiple lines, the highlighting goes past the end point of the match.  The amount it's "wrong" by increases with each additional newline inside the match itself.

### How to reproduce it (as minimally and precisely as possible)

Text -> Regex Tester
**Configuration:**  Ignore Case, Singleline

**Regular expression:** `<table.*?>.*?</table>`

**Text:**
`<table border="0" cellpadding="0" cellspacing="0" width="864" class="xl67" style="border-collapse:collapse; table-layout:fixed; width:651pt">
a
a
a
a
a
a
a
a
</table>
<p>CONFIDENTIALITY NOTICE:`

### Expected behavior

You would expect it to highlight from the start of `<table>` to the end of `</table>` but instead the highlighting goes to the end of `<p>CONFI`.  Adding another line inside the table tags of the text further offsets the highlighting.

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/61800093/21bb171e-ec82-4f6c-88b9-cee2f3fca103)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

**Comment by alexclarkmusa** [comment]
I apologize in advance - markdown is messing with the HTML I was using in this example.  I'm adding a screenshot of what the text to search actually looks like:
![image](https://github.com/DevToys-app/DevToys/assets/61800093/6ababb38-7b45-4549-bc0d-813253bb8e1a)

**Comment by veler** [comment]
Hi,
This is fixed in DevToys 2.0, which will be released in a few weeks.
