### ISSUE TITLE
File Consolidation Tool

### ISSUE THREAD

**Issue by me-manikanta** [DevToys-app/DevToys#1177]
### What feature or new tool do you think should be added to DevToys?

A feature that takes multiple input files of various formats (e.g., JSON, text) and consolidates them into a single output file, merging contents appropriately based on file type.

### Why do you think this is needed?

This tool would streamline workflows that involve managing and combining multiple files. For JSON files, it could merge objects; for text files, it could concatenate content. This saves time and reduces the complexity of manual file handling.

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
