### ISSUE TITLE
DevToys crashed when startuped

### ISSUE THREAD

**Issue by 19wym99** [DevToys-app/DevToys#1178]
### Current behavior

After a few seconds of normal startup, devtoys crashes. I have tried uninstalling, reinstalling, and resetting the application data, but this issue still occurs. The version is V1.0.13.0, and my operating system is Windows 10 22H2. Can you please help me troubleshoot this issue? 
What I can think of are some methods: ① Insufficient memory, program crashes, ② Antivirus software or certain software that terminates the normal startup of Devtoys, ③ Lack of necessary runtime libraries. If possible, please help me solve the problem. Thank you for your help

### How to reproduce it (as minimally and precisely as possible)

① Use the installation package with the. msixbundle suffix of devtoys for the installation process 
② Start DevToys normally

### Expected behavior

DevToys startup without crashing

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.13.0

**Comment by veler** [comment]
Hi,
We just released DevToys 2.0. Please try and tell us if the problem still happen. See https://devtoys.app

**Comment by dncoder** [comment]
I have the same issue as well with the latest version [v2.0.1.0](https://github.com/DevToys-app/DevToys/releases/tag/v2.0.1.0). When I start it, an empty window appears for a second then it crashes silently. I didn't find any logs in the program directory or any information on how to enable logging, is it even possible?
