### ISSUE TITLE
Missing DevToys.Api namespace

### ISSUE THREAD

**Issue by toczekmj** [DevToys-app/DevToys#1184]
### Current behavior

Hi! I don't know how much it's about DevToys itself, but I found weird issue, while following [This guide](https://github.com/DevToys-app/Documentation/blob/main/articles/extension-development/getting-started/create-an-extension.md). Everything seems fine till the "Create a Resource Assembly Identifier", namely I have encountered this error 
![image](https://github.com/DevToys-app/DevToys/assets/13023170/d6638726-29ff-400c-ac04-0ac786f3fc41)
while referencing DevToys.Api; 
![image](https://github.com/DevToys-app/DevToys/assets/13023170/3f2edcf3-376c-4d5e-943b-91abb5168469)

### How to reproduce it (as minimally and precisely as possible)

** Minimal Extension - I am using Visual Studio 2022 ** 
1. I have created Class Library and set project to use .NET 8.0 
2. I have performed "dotnet add package DevToys.Api --version VERSION_NUMBER" where VERSION_NUMBER = 2.0.0-preview.3 as it's the latest at the time i am writing this 
3. Later on I did create .resx file and set all the properties 
4. When i moved on to "Create a Resource Assembly Identifier" and added provided code with DevToys.Api and System.ComponentModel.Composition I've gotten red underline saying that those components are not found. Since System.ComponentModel.Composition is avaliable as separate nuget package I've choosen to install it standalone.
5. To conclude after completing all above steps there is still problem with  DevToys namespace and IResourceAssemblyIdentifier is as you might have guessed not available too.  (Also yes - I've red that sometimes project compiles even when VisualStudio shows an error, but in this case it does not Build / Compile at all.) 

### Expected behavior

Including Nuget package should give the access to DevToys.Api namespace.

### Workaround

There is an option to get it to work, but we will needs some additional tool called [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer).

1. Go to [NuGet package page](https://www.nuget.org/packages/DevToys.Api/) and download package file
2. Install and open NuGet package explorer 
3. Open file downloaded in step 1 
4. In the "Package contents" window expand lib -> net8.0 
5. Right-click on DevToys.Api.dll -> Save As and save it anywhere you want 
6. Go to Visual Studio
7. Click on Project -> Add Project Reference -> Browse and select exported .dll  and selecet OK 
8. Red underline is gone and we can build the project ![image](https://github.com/DevToys-app/DevToys/assets/13023170/7751dbae-7155-4028-90db-260d5ce1a29b)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Not applicable I think

**Comment by toczekmj** [comment]
Okay, I've examined .csproj file and in comparision to other NuGet's there is something weird going on, at least basic on my knowledge. 
The problem can be easili fixed by just commenting out theese two lines:
![image](https://github.com/DevToys-app/DevToys/assets/13023170/c4c2a76b-f556-4731-8db7-cec9e5c7593d)

Having in mind that PrivateAssets are set to all, shouldn't they be available anyway based on how IncludeAssets are configured? I've tried to do some research but i don't get it at all. @veler

**Comment by veler** [comment]
Hi,
Thanks for sharing and investigating it.
It's interesting that dotnet added these 2 lines. They are indeed not needed, as we use it this way in DevToys.Tools and DevToys.PngCompressor: https://github.com/DevToys-app/DevToys.PngCompressor/blob/cafb5a572f4b619ddb735ced0f01b3bafbcecef2/src/DevToys.PngCompressor/DevToys.PngCompressor.csproj#L19

I will close the issue for now as you're unblocked. 
Thanks
