### ISSUE TITLE
File Permissions - devtoys_linux_x64_portable

### ISSUE THREAD

**Issue by pjobson** [DevToys-app/DevToys#1189]
### Current behavior

Many  files are set to executable permissions for no reason. `DevToys.Linux` is correctly set to 755, others are 764.

### How to reproduce it (as minimally and precisely as possible)

    find . -type f -perm 764

### Expected behavior

I expect files to have the correct permissions.

### Affected platforms

Linux

### Affected DevToys kind

DevToys (app with GUI), DevToys CLI

### DevToys Version

2.0.1.0

**Comment by veler** [comment]
Hi @pjobson ,

Thanks for reporting this issue. Did you install DevToys through the ZIP or through the DEB file?

Hi @kforeverisback, any insight on why this would happen?

Thanks :)

**Comment by pjobson** [comment]
@veler the zip file.

     wget https://github.com/DevToys-app/DevToys/releases/download/v2.0.1.0/devtoys_linux_x64_portable.zip
     unzip devtoys_linux_x64_portable.zip 
     find . -type f -perm 764

Returns:

     ./Microsoft.Extensions.FileSystemGlobbing.dll
     ./System.Globalization.Extensions.dll
     ./Microsoft.AspNetCore.Components.Web.dll
     ./System.Transactions.Local.dll
     ./System.Threading.ThreadPool.dll
     ./System.Runtime.InteropServices.dll
     ./WindowsBase.dll
     ./System.Security.Cryptography.Encoding.dll
     ./libclrjit.so
     ./System.Formats.Tar.dll
     ./System.Reflection.Emit.dll
     ./System.Reflection.Emit.ILGeneration.dll
     ./System.Collections.dll
     ./System.Security.Cryptography.dll
     ./System.Security.Cryptography.OpenSsl.dll
     ./Microsoft.Extensions.Configuration.Abstractions.dll
     ./FuzzySharp.dll
     ./Markdig.dll
     ./Microsoft.AspNetCore.Metadata.dll
     ./System.Memory.dll
     ./System.Security.Cryptography.Algorithms.dll
     ./System.Formats.Asn1.dll
     ./System.IO.Compression.Brotli.dll
     ./System.IO.FileSystem.Watcher.dll
     ./System.Runtime.CompilerServices.VisualC.dll
     ./System.Runtime.Serialization.Primitives.dll
     ./Adw-1.dll
     ./System.ValueTuple.dll
     ./Microsoft.AspNetCore.Components.dll
     ./System.Collections.Immutable.dll
     ./System.Runtime.Intrinsics.dll
     ./System.Security.Cryptography.Cng.dll
     ./Microsoft.Extensions.FileProviders.Composite.dll
     ./System.Runtime.Serialization.Formatters.dll
     ./System.Globalization.Calendars.dll
     ./Microsoft.Extensions.Logging.Abstractions.dll
     ./System.Security.AccessControl.dll
     ./NuGet.Frameworks.dll
     ./Microsoft.JSInterop.dll
     ./System.Resources.ResourceManager.dll
     ./System.ComponentModel.TypeConverter.dll
     ./JavaScriptCore-6.0.dll
     ./System.Xml.XmlSerializer.dll
     ./System.Net.NetworkInformation.dll
     ./System.Diagnostics.TraceSource.dll
     ./Microsoft.Win32.Primitives.dll
     ./System.IO.FileSystem.AccessControl.dll
     ./System.Net.Security.dll
     ./System.Drawing.Primitives.dll
     ./System.IO.dll
     ./System.Data.Common.dll
     ./NuGet.Versioning.dll
     ./System.Linq.Parallel.dll
     ./libhostfxr.so
     ./System.Private.Xml.Linq.dll
     ./libcoreclrtraceptprovider.so
     ./System.Threading.dll
     ./System.Dynamic.Runtime.dll
     ./System.Drawing.dll
     ./GdkPixbuf-2.0.dll
     ./Microsoft.Win32.Registry.dll
     ./System.Security.Claims.dll
     ./System.Numerics.Vectors.dll
     ./System.Xml.ReaderWriter.dll
     ./System.Resources.Reader.dll
     ./System.Private.CoreLib.dll
     ./System.IO.UnmanagedMemoryStream.dll
     ./System.Net.WebSockets.Client.dll
     ./System.ServiceProcess.dll
     ./System.Xml.XPath.XDocument.dll
     ./System.IO.Compression.FileSystem.dll
     ./System.IO.FileSystem.dll
     ./System.Net.dll
     ./libSystem.Globalization.Native.so
     ./System.Net.HttpListener.dll
     ./freetype2-2.0.dll
     ./System.Reflection.Extensions.dll
     ./CommunityToolkit.Common.dll
     ./System.Linq.Queryable.dll
     ./Microsoft.Extensions.Primitives.dll
     ./Gsk-4.0.dll
     ./System.Runtime.Loader.dll
     ./Gtk-4.0.dll
     ./System.Threading.Tasks.Extensions.dll
     ./System.Net.Mail.dll
     ./System.Xml.dll
     ./System.Diagnostics.FileVersionInfo.dll
     ./System.Runtime.Extensions.dll
     ./Microsoft.Extensions.FileProviders.Embedded.dll
     ./System.ComponentModel.Annotations.dll
     ./libSystem.Net.Security.Native.so
     ./System.Net.Requests.dll
     ./System.Private.DataContractSerialization.dll
     ./GObject-2.0.dll
     ./System.Web.HttpUtility.dll
     ./System.Linq.Expressions.dll
     ./System.IO.IsolatedStorage.dll
     ./PangoCairo-1.0.dll
     ./System.Diagnostics.StackTrace.dll
     ./System.Text.RegularExpressions.dll
     ./System.Numerics.dll
     ./System.IO.Compression.ZipFile.dll
     ./System.Xml.XmlDocument.dll
     ./System.Collections.NonGeneric.dll
     ./System.Runtime.CompilerServices.Unsafe.dll
     ./Soup-3.0.dll
     ./System.Diagnostics.Debug.dll
     ./System.Net.WebClient.dll
     ./System.Security.Cryptography.Csp.dll
     ./libSystem.IO.Compression.Native.so
     ./System.ComponentModel.dll
     ./System.Threading.Tasks.Parallel.dll
     ./libmscordbi.so
     ./System.Web.dll
     ./System.Diagnostics.Tools.dll
     ./SixLabors.ImageSharp.dll
     ./System.Runtime.Serialization.Json.dll
     ./System.Security.Cryptography.Pkcs.dll
     ./System.Reflection.TypeExtensions.dll
     ./System.Security.Cryptography.X509Certificates.dll
     ./System.Runtime.Numerics.dll
     ./System.IO.MemoryMappedFiles.dll
     ./Gdk-4.0.dll
     ./libmscordaccore.so
     ./System.Xml.Serialization.dll
     ./System.Reflection.dll
     ./System.Private.Xml.dll
     ./System.Core.dll
     ./System.Threading.Tasks.Dataflow.dll
     ./System.Threading.Thread.dll
     ./System.Runtime.Serialization.dll
     ./System.Net.Primitives.dll
     ./OneOf.dll
     ./System.Data.dll
     ./System.Diagnostics.Process.dll
     ./System.Collections.Specialized.dll
     ./Microsoft.AspNetCore.Components.Forms.dll
     ./Microsoft.Extensions.FileProviders.Abstractions.dll
     ./System.Security.dll
     ./System.Xml.XDocument.dll
     ./System.dll
     ./Microsoft.AspNetCore.Components.WebView.dll
     ./CommunityToolkit.Diagnostics.dll
     ./System.Reflection.Primitives.dll
     ./System.Net.Http.Json.dll
     ./System.ComponentModel.Composition.dll
     ./System.Threading.Tasks.dll
     ./libSystem.Security.Cryptography.Native.OpenSsl.so
     ./System.Runtime.Handles.dll
     ./Microsoft.Extensions.FileProviders.Physical.dll
     ./System.Reflection.Emit.Lightweight.dll
     ./System.Diagnostics.Contracts.dll
     ./System.ObjectModel.dll
     ./System.Buffers.dll
     ./Microsoft.Extensions.Options.dll
     ./System.Threading.Timer.dll
     ./System.Private.Uri.dll
     ./System.IO.FileSystem.Primitives.dll
     ./Microsoft.AspNetCore.Authorization.dll
     ./Microsoft.VisualBasic.dll
     ./Microsoft.VisualBasic.Core.dll
     ./GLib-2.0.dll
     ./System.Net.WebSockets.dll
     ./System.Xml.XPath.dll
     ./NuGet.Configuration.dll
     ./createdump
     ./Graphene-1.0.dll
     ./Microsoft.Extensions.Configuration.Binder.dll
     ./System.Net.WebProxy.dll
     ./System.Transactions.dll
     ./System.Text.Encoding.CodePages.dll
     ./HarfBuzz-0.0.dll
     ./System.Resources.Writer.dll
     ./Microsoft.Extensions.DependencyInjection.Abstractions.dll
     ./System.Net.WebHeaderCollection.dll
     ./System.Security.SecureString.dll
     ./System.Runtime.Serialization.Xml.dll
     ./System.Xml.Linq.dll
     ./NuGet.Packaging.dll
     ./System.Security.Principal.Windows.dll
     ./System.Linq.dll
     ./libcoreclr.so
     ./libclrgc.so
     ./System.Data.DataSetExtensions.dll
     ./System.IO.FileSystem.DriveInfo.dll
     ./Microsoft.Extensions.Logging.Debug.dll
     ./Pango-1.0.dll
     ./System.IO.Pipes.dll
     ./System.IO.Pipelines.dll
     ./System.Net.Http.dll
     ./System.Diagnostics.Tracing.dll
     ./Newtonsoft.Json.dll
     ./System.Net.Ping.dll
     ./System.IO.Compression.dll
     ./Microsoft.Extensions.Configuration.dll
     ./System.Security.Cryptography.ProtectedData.dll
     ./libhostpolicy.so
     ./System.Text.Encodings.Web.dll
     ./System.ServiceModel.Web.dll
     ./System.Diagnostics.DiagnosticSource.dll
     ./System.Configuration.dll
     ./mscorlib.dll
     ./NuGet.Common.dll
     ./WebKit-6.0.dll
     ./System.Net.Quic.dll
     ./System.Net.Sockets.dll
     ./cairo-1.0.dll
     ./System.Text.Encoding.dll
     ./Gio-2.0.dll
     ./System.AppContext.dll
     ./System.Net.ServicePoint.dll
     ./System.Reflection.DispatchProxy.dll
     ./Microsoft.Extensions.DependencyInjection.dll
     ./System.Threading.Overlapped.dll
     ./System.Text.Json.dll
     ./System.Text.Encoding.Extensions.dll
     ./System.Security.Principal.dll
     ./libSystem.Native.so
     ./Microsoft.CSharp.dll
     ./System.Runtime.InteropServices.JavaScript.dll
     ./System.Reflection.Metadata.dll
     ./Microsoft.Extensions.Configuration.FileExtensions.dll
     ./System.IO.Pipes.AccessControl.dll
     ./Microsoft.Extensions.Logging.dll
     ./System.Security.Cryptography.Primitives.dll
     ./System.Diagnostics.TextWriterTraceListener.dll
     ./System.ComponentModel.Primitives.dll
     ./System.Net.NameResolution.dll
     ./System.Runtime.dll
     ./System.Collections.Concurrent.dll
     ./System.Globalization.dll
     ./netstandard.dll
     ./System.Windows.dll
     ./System.ComponentModel.DataAnnotations.dll
     ./System.ComponentModel.EventBasedAsync.dll
     ./CommunityToolkit.Mvvm.dll
     ./System.Runtime.InteropServices.RuntimeInformation.dll
     ./Microsoft.Extensions.Configuration.Json.dll
     ./System.Console.dll
     ./System.Threading.Channels.dll

I chmod'd them to 644 and it runs.

**Comment by pjobson** [comment]
The deb file has incorrect permissions, also.  I'd venture to guess all the archives do, but I'm not checking.  

Here's the deb file.

     wget https://github.com/DevToys-app/DevToys/releases/download/v2.0.1.0/devtoys_linux_x64.deb
     unar devtoys_linux_x64.deb
     zstd -d devtoys_linux_x64/data.tar.zst
     tar xvf devtoys_linux_x64/data.tar
     find . -type f -perm 755

This shows a lot of incorrectly permissioned dll files.

Also the opt pathing is kind of weird, why /opt/devtoys/devtoys/ ... Though I don't want to get outside of the scope of this issue.

     ./opt/devtoys/devtoys/Microsoft.Extensions.FileSystemGlobbing.dll
     ./opt/devtoys/devtoys/System.Globalization.Extensions.dll
     ./opt/devtoys/devtoys/Microsoft.AspNetCore.Components.Web.dll
     ./opt/devtoys/devtoys/System.Transactions.Local.dll
     ./opt/devtoys/devtoys/System.Threading.ThreadPool.dll
     ./opt/devtoys/devtoys/System.Runtime.InteropServices.dll
     ./opt/devtoys/devtoys/WindowsBase.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.Encoding.dll
     ./opt/devtoys/devtoys/System.Formats.Tar.dll
     ./opt/devtoys/devtoys/System.Reflection.Emit.dll
     ./opt/devtoys/devtoys/System.Reflection.Emit.ILGeneration.dll
     ./opt/devtoys/devtoys/System.Collections.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.OpenSsl.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Configuration.Abstractions.dll
     ./opt/devtoys/devtoys/FuzzySharp.dll
     ./opt/devtoys/devtoys/Markdig.dll
     ./opt/devtoys/devtoys/Microsoft.AspNetCore.Metadata.dll
     ./opt/devtoys/devtoys/System.Memory.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.Algorithms.dll
     ./opt/devtoys/devtoys/System.Formats.Asn1.dll
     ./opt/devtoys/devtoys/System.IO.Compression.Brotli.dll
     ./opt/devtoys/devtoys/System.IO.FileSystem.Watcher.dll
     ./opt/devtoys/devtoys/System.Runtime.CompilerServices.VisualC.dll
     ./opt/devtoys/devtoys/System.Runtime.Serialization.Primitives.dll
     ./opt/devtoys/devtoys/Adw-1.dll
     ./opt/devtoys/devtoys/System.ValueTuple.dll
     ./opt/devtoys/devtoys/Microsoft.AspNetCore.Components.dll
     ./opt/devtoys/devtoys/System.Collections.Immutable.dll
     ./opt/devtoys/devtoys/System.Runtime.Intrinsics.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.Cng.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.FileProviders.Composite.dll
     ./opt/devtoys/devtoys/System.Runtime.Serialization.Formatters.dll
     ./opt/devtoys/devtoys/System.Globalization.Calendars.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Logging.Abstractions.dll
     ./opt/devtoys/devtoys/System.Security.AccessControl.dll
     ./opt/devtoys/devtoys/NuGet.Frameworks.dll
     ./opt/devtoys/devtoys/Microsoft.JSInterop.dll
     ./opt/devtoys/devtoys/System.Resources.ResourceManager.dll
     ./opt/devtoys/devtoys/System.ComponentModel.TypeConverter.dll
     ./opt/devtoys/devtoys/JavaScriptCore-6.0.dll
     ./opt/devtoys/devtoys/System.Xml.XmlSerializer.dll
     ./opt/devtoys/devtoys/System.Net.NetworkInformation.dll
     ./opt/devtoys/devtoys/System.Diagnostics.TraceSource.dll
     ./opt/devtoys/devtoys/Microsoft.Win32.Primitives.dll
     ./opt/devtoys/devtoys/System.IO.FileSystem.AccessControl.dll
     ./opt/devtoys/devtoys/System.Net.Security.dll
     ./opt/devtoys/devtoys/System.Drawing.Primitives.dll
     ./opt/devtoys/devtoys/System.IO.dll
     ./opt/devtoys/devtoys/System.Data.Common.dll
     ./opt/devtoys/devtoys/NuGet.Versioning.dll
     ./opt/devtoys/devtoys/System.Linq.Parallel.dll
     ./opt/devtoys/devtoys/System.Private.Xml.Linq.dll
     ./opt/devtoys/devtoys/System.Threading.dll
     ./opt/devtoys/devtoys/System.Dynamic.Runtime.dll
     ./opt/devtoys/devtoys/System.Drawing.dll
     ./opt/devtoys/devtoys/GdkPixbuf-2.0.dll
     ./opt/devtoys/devtoys/Microsoft.Win32.Registry.dll
     ./opt/devtoys/devtoys/System.Security.Claims.dll
     ./opt/devtoys/devtoys/System.Numerics.Vectors.dll
     ./opt/devtoys/devtoys/System.Xml.ReaderWriter.dll
     ./opt/devtoys/devtoys/System.Resources.Reader.dll
     ./opt/devtoys/devtoys/System.Private.CoreLib.dll
     ./opt/devtoys/devtoys/System.IO.UnmanagedMemoryStream.dll
     ./opt/devtoys/devtoys/System.Net.WebSockets.Client.dll
     ./opt/devtoys/devtoys/System.ServiceProcess.dll
     ./opt/devtoys/devtoys/System.Xml.XPath.XDocument.dll
     ./opt/devtoys/devtoys/System.IO.Compression.FileSystem.dll
     ./opt/devtoys/devtoys/System.IO.FileSystem.dll
     ./opt/devtoys/devtoys/System.Net.dll
     ./opt/devtoys/devtoys/System.Net.HttpListener.dll
     ./opt/devtoys/devtoys/freetype2-2.0.dll
     ./opt/devtoys/devtoys/System.Reflection.Extensions.dll
     ./opt/devtoys/devtoys/CommunityToolkit.Common.dll
     ./opt/devtoys/devtoys/System.Linq.Queryable.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Primitives.dll
     ./opt/devtoys/devtoys/Gsk-4.0.dll
     ./opt/devtoys/devtoys/System.Runtime.Loader.dll
     ./opt/devtoys/devtoys/Gtk-4.0.dll
     ./opt/devtoys/devtoys/System.Threading.Tasks.Extensions.dll
     ./opt/devtoys/devtoys/System.Net.Mail.dll
     ./opt/devtoys/devtoys/System.Xml.dll
     ./opt/devtoys/devtoys/System.Diagnostics.FileVersionInfo.dll
     ./opt/devtoys/devtoys/System.Runtime.Extensions.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.FileProviders.Embedded.dll
     ./opt/devtoys/devtoys/System.ComponentModel.Annotations.dll
     ./opt/devtoys/devtoys/System.Net.Requests.dll
     ./opt/devtoys/devtoys/System.Private.DataContractSerialization.dll
     ./opt/devtoys/devtoys/GObject-2.0.dll
     ./opt/devtoys/devtoys/System.Web.HttpUtility.dll
     ./opt/devtoys/devtoys/System.Linq.Expressions.dll
     ./opt/devtoys/devtoys/System.IO.IsolatedStorage.dll
     ./opt/devtoys/devtoys/PangoCairo-1.0.dll
     ./opt/devtoys/devtoys/System.Diagnostics.StackTrace.dll
     ./opt/devtoys/devtoys/System.Text.RegularExpressions.dll
     ./opt/devtoys/devtoys/System.Numerics.dll
     ./opt/devtoys/devtoys/System.IO.Compression.ZipFile.dll
     ./opt/devtoys/devtoys/System.Xml.XmlDocument.dll
     ./opt/devtoys/devtoys/System.Collections.NonGeneric.dll
     ./opt/devtoys/devtoys/System.Runtime.CompilerServices.Unsafe.dll
     ./opt/devtoys/devtoys/Soup-3.0.dll
     ./opt/devtoys/devtoys/System.Diagnostics.Debug.dll
     ./opt/devtoys/devtoys/System.Net.WebClient.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.Csp.dll
     ./opt/devtoys/devtoys/System.ComponentModel.dll
     ./opt/devtoys/devtoys/System.Threading.Tasks.Parallel.dll
     ./opt/devtoys/devtoys/System.Web.dll
     ./opt/devtoys/devtoys/System.Diagnostics.Tools.dll
     ./opt/devtoys/devtoys/SixLabors.ImageSharp.dll
     ./opt/devtoys/devtoys/System.Runtime.Serialization.Json.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.Pkcs.dll
     ./opt/devtoys/devtoys/System.Reflection.TypeExtensions.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.X509Certificates.dll
     ./opt/devtoys/devtoys/System.Runtime.Numerics.dll
     ./opt/devtoys/devtoys/System.IO.MemoryMappedFiles.dll
     ./opt/devtoys/devtoys/Gdk-4.0.dll
     ./opt/devtoys/devtoys/System.Xml.Serialization.dll
     ./opt/devtoys/devtoys/System.Reflection.dll
     ./opt/devtoys/devtoys/System.Private.Xml.dll
     ./opt/devtoys/devtoys/System.Core.dll
     ./opt/devtoys/devtoys/System.Threading.Tasks.Dataflow.dll
     ./opt/devtoys/devtoys/System.Threading.Thread.dll
     ./opt/devtoys/devtoys/System.Runtime.Serialization.dll
     ./opt/devtoys/devtoys/System.Net.Primitives.dll
     ./opt/devtoys/devtoys/OneOf.dll
     ./opt/devtoys/devtoys/System.Data.dll
     ./opt/devtoys/devtoys/System.Diagnostics.Process.dll
     ./opt/devtoys/devtoys/System.Collections.Specialized.dll
     ./opt/devtoys/devtoys/Microsoft.AspNetCore.Components.Forms.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.FileProviders.Abstractions.dll
     ./opt/devtoys/devtoys/System.Security.dll
     ./opt/devtoys/devtoys/System.Xml.XDocument.dll
     ./opt/devtoys/devtoys/System.dll
     ./opt/devtoys/devtoys/Microsoft.AspNetCore.Components.WebView.dll
     ./opt/devtoys/devtoys/CommunityToolkit.Diagnostics.dll
     ./opt/devtoys/devtoys/System.Reflection.Primitives.dll
     ./opt/devtoys/devtoys/System.Net.Http.Json.dll
     ./opt/devtoys/devtoys/System.ComponentModel.Composition.dll
     ./opt/devtoys/devtoys/System.Threading.Tasks.dll
     ./opt/devtoys/devtoys/System.Runtime.Handles.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.FileProviders.Physical.dll
     ./opt/devtoys/devtoys/System.Reflection.Emit.Lightweight.dll
     ./opt/devtoys/devtoys/System.Diagnostics.Contracts.dll
     ./opt/devtoys/devtoys/System.ObjectModel.dll
     ./opt/devtoys/devtoys/System.Buffers.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Options.dll
     ./opt/devtoys/devtoys/System.Threading.Timer.dll
     ./opt/devtoys/devtoys/System.Private.Uri.dll
     ./opt/devtoys/devtoys/System.IO.FileSystem.Primitives.dll
     ./opt/devtoys/devtoys/Microsoft.AspNetCore.Authorization.dll
     ./opt/devtoys/devtoys/Microsoft.VisualBasic.dll
     ./opt/devtoys/devtoys/Microsoft.VisualBasic.Core.dll
     ./opt/devtoys/devtoys/GLib-2.0.dll
     ./opt/devtoys/devtoys/System.Net.WebSockets.dll
     ./opt/devtoys/devtoys/System.Xml.XPath.dll
     ./opt/devtoys/devtoys/NuGet.Configuration.dll
     ./opt/devtoys/devtoys/createdump
     ./opt/devtoys/devtoys/Graphene-1.0.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Configuration.Binder.dll
     ./opt/devtoys/devtoys/System.Net.WebProxy.dll
     ./opt/devtoys/devtoys/System.Transactions.dll
     ./opt/devtoys/devtoys/System.Text.Encoding.CodePages.dll
     ./opt/devtoys/devtoys/HarfBuzz-0.0.dll
     ./opt/devtoys/devtoys/System.Resources.Writer.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.DependencyInjection.Abstractions.dll
     ./opt/devtoys/devtoys/DevToys.Linux
     ./opt/devtoys/devtoys/System.Net.WebHeaderCollection.dll
     ./opt/devtoys/devtoys/System.Security.SecureString.dll
     ./opt/devtoys/devtoys/System.Runtime.Serialization.Xml.dll
     ./opt/devtoys/devtoys/System.Xml.Linq.dll
     ./opt/devtoys/devtoys/NuGet.Packaging.dll
     ./opt/devtoys/devtoys/System.Security.Principal.Windows.dll
     ./opt/devtoys/devtoys/System.Linq.dll
     ./opt/devtoys/devtoys/System.Data.DataSetExtensions.dll
     ./opt/devtoys/devtoys/System.IO.FileSystem.DriveInfo.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Logging.Debug.dll
     ./opt/devtoys/devtoys/Pango-1.0.dll
     ./opt/devtoys/devtoys/System.IO.Pipes.dll
     ./opt/devtoys/devtoys/System.IO.Pipelines.dll
     ./opt/devtoys/devtoys/System.Net.Http.dll
     ./opt/devtoys/devtoys/System.Diagnostics.Tracing.dll
     ./opt/devtoys/devtoys/Newtonsoft.Json.dll
     ./opt/devtoys/devtoys/System.Net.Ping.dll
     ./opt/devtoys/devtoys/System.IO.Compression.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Configuration.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.ProtectedData.dll
     ./opt/devtoys/devtoys/System.Text.Encodings.Web.dll
     ./opt/devtoys/devtoys/System.ServiceModel.Web.dll
     ./opt/devtoys/devtoys/System.Diagnostics.DiagnosticSource.dll
     ./opt/devtoys/devtoys/System.Configuration.dll
     ./opt/devtoys/devtoys/mscorlib.dll
     ./opt/devtoys/devtoys/NuGet.Common.dll
     ./opt/devtoys/devtoys/WebKit-6.0.dll
     ./opt/devtoys/devtoys/System.Net.Quic.dll
     ./opt/devtoys/devtoys/System.Net.Sockets.dll
     ./opt/devtoys/devtoys/cairo-1.0.dll
     ./opt/devtoys/devtoys/System.Text.Encoding.dll
     ./opt/devtoys/devtoys/Gio-2.0.dll
     ./opt/devtoys/devtoys/System.AppContext.dll
     ./opt/devtoys/devtoys/System.Net.ServicePoint.dll
     ./opt/devtoys/devtoys/System.Reflection.DispatchProxy.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.DependencyInjection.dll
     ./opt/devtoys/devtoys/System.Threading.Overlapped.dll
     ./opt/devtoys/devtoys/System.Text.Json.dll
     ./opt/devtoys/devtoys/System.Text.Encoding.Extensions.dll
     ./opt/devtoys/devtoys/System.Security.Principal.dll
     ./opt/devtoys/devtoys/Microsoft.CSharp.dll
     ./opt/devtoys/devtoys/System.Runtime.InteropServices.JavaScript.dll
     ./opt/devtoys/devtoys/System.Reflection.Metadata.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Configuration.FileExtensions.dll
     ./opt/devtoys/devtoys/System.IO.Pipes.AccessControl.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Logging.dll
     ./opt/devtoys/devtoys/System.Security.Cryptography.Primitives.dll
     ./opt/devtoys/devtoys/System.Diagnostics.TextWriterTraceListener.dll
     ./opt/devtoys/devtoys/System.ComponentModel.Primitives.dll
     ./opt/devtoys/devtoys/System.Net.NameResolution.dll
     ./opt/devtoys/devtoys/System.Runtime.dll
     ./opt/devtoys/devtoys/System.Collections.Concurrent.dll
     ./opt/devtoys/devtoys/System.Globalization.dll
     ./opt/devtoys/devtoys/netstandard.dll
     ./opt/devtoys/devtoys/System.Windows.dll
     ./opt/devtoys/devtoys/System.ComponentModel.DataAnnotations.dll
     ./opt/devtoys/devtoys/System.ComponentModel.EventBasedAsync.dll
     ./opt/devtoys/devtoys/CommunityToolkit.Mvvm.dll
     ./opt/devtoys/devtoys/System.Runtime.InteropServices.RuntimeInformation.dll
     ./opt/devtoys/devtoys/Microsoft.Extensions.Configuration.Json.dll
     ./opt/devtoys/devtoys/System.Console.dll
     ./opt/devtoys/devtoys/System.Threading.Channels.dll

**Comment by kforeverisback** [comment]
@veler That I am not so sure. For some reason, some of my projects the dlls produced are marked executable, and for other projects they aren't. I searched dotnet forums for something, but no avail.
I think the best solution for now is to manually do `chmod -x *.dll` before packaging.

**Comment by veler** [comment]
Thank you! I will try that !

**Comment by veler** [comment]
It works, thanks! :D
