### ISSUE TITLE
Windows color accent fully changes the UI theme

### ISSUE THREAD

**Issue by Mikaz-fr** [DevToys-app/DevToys#1191]
### Current behavior

On Windows 10 the UI theme is fully picking up the OS color accent (see screenshots).
This happens when an accent is set and option "Title bars and window borders" is enabled.
I would expect that the UI respect the them Dark / Light option instead, I don't want to change my accent for the UI to look dark.
I'm using DevToys 2.0-preview.1 portable x64.

### How to reproduce it (as minimally and precisely as possible)

In Windows 10 setting set a Color accent `Settings -> Personalization -> Colors` and enable "Title bars and windows borders" under section "Show accent color on the following surfaces" (see screenshots).
Start DevToys 2.0-preview.1 and see the color being overall the UI.

### Expected behavior

The UI theme to remain dark even when Colors accent option "Title bars and window borders" is enabled.

### Screenshots

UI look with option "Title bars and window borders" enabled:
![accent_pr1](https://github.com/DevToys-app/DevToys/assets/2411679/24ef2830-2fd1-499d-a4c4-e88a61caff6d)

Without option "Title bars and window borders" enabled:
![accent_pr2](https://github.com/DevToys-app/DevToys/assets/2411679/387fd97e-739f-4ad8-bbb9-deaff91910aa)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

DevToys 2.0-preview.1 portable x64

**Comment by Mikaz-fr** [comment]
I searched the repo and found that it might be related to pull request https://github.com/DevToys-app/DevToys/pull/112. 
But the screenshot there had option "Title bars and windows borders" disabled so I don't know if the behavior was the same.

**Comment by veler** [comment]
Thanks! I got a fix here: https://github.com/DevToys-app/DevToys/pull/1223

**Comment by andercard0** [comment]
Hi, 

I'm not sure if this is related but take a look in the gif, the problem is, the dark theme isn't being applied correctly, tried to set up as system default but no deal it stays in blue, but, if i change the focus window it returns to black/dark theme. 

If is not related please let me know and I'll raise a issue.
![bug](https://github.com/DevToys-app/DevToys/assets/43047877/591e05b7-1b49-4308-a7c9-be4865ab650c)

**Comment by veler** [comment]
Hi @andercard0,
It's related, and my pull request address this issue too :)

**Comment by andercard0** [comment]
> Hi @andercard0,
> It's related, and my pull request address this issue too :)

Great thanks. I will for the artefacts in mentioned PR.

**Comment by veler** [comment]
Thanks. A fix is available in DevToys 2.0.2.0
