### ISSUE TITLE
Typo in Polish language

### ISSUE THREAD

**Issue by AdrianMaj** [DevToys-app/DevToys#1192]
### Current behavior

![image](https://github.com/DevToys-app/DevToys/assets/123100543/f44093b4-7ef7-4ae2-9123-fd594578b1fd)

As you can see, the red frame has a typo in it. Text should be like in the green box - "Bezstratny" instead of "Bezstranty".

### How to reproduce it (as minimally and precisely as possible)

1. Switch to Polish language
2. Go to "Grafika" tab.
3. See first element

### Expected behavior

Fix typo

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.14.0

**Comment by veler** [comment]
Thanks for reporting this! I'm not speaking a word of Polish and don't feel comfortable addressing it myself. If you're up to it (or anyone reading this), you can improve the translation using Crowdin. Here is how: https://github.com/DevToys-app/DevToys/blob/main/CONTRIBUTING.md#internationalization-and-localization
Thanks !
