### ISSUE TITLE
Image conversion to and from WebP feature

### ISSUE THREAD

**Issue by AdrianMaj** [DevToys-app/DevToys#1193]
### What feature or new tool do you think should be added to DevToys?

Convert images from png/jpg/jpeg/bmp to .webp and vice versa. 

### Why do you think this is needed?

Many of the web developers use .webp format to provide images for their websites or web applications, and I think it would be a great feature. Also, an auto-compress option would be great :)

### Solution/Idea

Just add that option to the "Image converter" tool. I am not really into C#, so I can't provide any code at the moment.

**Comment by veler** [comment]
Hi,
It is supported in DevToys 2.0
![image](https://github.com/DevToys-app/DevToys/assets/3747805/1d7163e4-a3ef-4dee-a21c-3a3a13d8f62f)
