### ISSUE TITLE
Failed to create GBM buffer on Wayland

### ISSUE THREAD

**Issue by parkerlreed** [DevToys-app/DevToys#1196]
### Current behavior

When running the application within Plasma Wayland, GBM fails to initialize.

Arch Linux

```
local/dotnet-host 8.0.6.sdk106-1
    A generic driver for the .NET Core Command Line Interface
local/dotnet-runtime 8.0.6.sdk106-1
    The .NET Core runtime
local/dotnet-sdk 8.0.6.sdk106-1
    The .NET Core SDK
local/dotnet-targeting-pack 8.0.6.sdk106-1
    The .NET Core targeting pack
```

### How to reproduce it (as minimally and precisely as possible)

1. Compile on Linux with the build.sh script
2. Change to the DevTool.Linux binary folder
3. Run DevTools.Linux

### Expected behavior

Application UI rendering

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/841440/b510ae20-d1d0-49a4-9d5b-36e13b8ea1cd)

### Workaround

Forcing it to run within X11 compat does work

```
 WAYLAND_DISPLAY="" ./DevToys.Linux
```

### Affected platforms

Linux

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

git master

### Relevant Assets/Logs

```
(process:5545): Gtk-WARNING **: 13:00:06.009: Unknown key gtk-modules in /home/parker/.config/gtk-4.0/settings.ini

(process:5545): Adwaita-WARNING **: 13:00:06.020: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Failed to create GBM buffer of size 0x0: Invalid argument
```

**Comment by parkerlreed** [comment]
(Even running within X11, none of the default tools are showing up)

![image](https://github.com/DevToys-app/DevToys/assets/841440/9d67a287-02ec-41ac-9722-8f5513cd2d24)

**Comment by badcel** [comment]
It is expected that no tools show up as their source is in a separate repository.

See the corresponding [Contributing.md](https://github.com/DevToys-app/DevToys.Tools/blob/main/CONTRIBUTING.md)

**Comment by parkerlreed** [comment]
Huh, it just started working randomly on Wayland. Not sure what was going on there.

Thanks for the response!
