### ISSUE TITLE
Dark mode unusable

### ISSUE THREAD

**Issue by Dessyreqt** [DevToys-app/DevToys#1197]
### Current behavior

On Windows 10, all of the side menu options are not viewable when the application is in Dark mode, and other elements are low contrast.

### How to reproduce it (as minimally and precisely as possible)

In Windows 10, set the App Theme to "Dark" mode, or "Use system settings" if your OS is in Dark mode.

### Expected behavior

Application should have labels that are viewable and a little more contrast between the text and background.

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/12574786/d00088c0-2dd4-4390-b1fc-d77a929d69c6)

### Workaround

Set the application to Light mode and wear some welding goggles.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.1

**Comment by Mikaz-fr** [comment]
Could this be related to https://github.com/DevToys-app/DevToys/issues/1191 ?
Did you try disabling the colors accent to see if it changes anything ?

**Comment by Dessyreqt** [comment]
I don't see an option for that in the app... and you can't deselect the accent color in windows. I already have the accent color not showing as much as possible:

![image](https://github.com/DevToys-app/DevToys/assets/12574786/b946f61b-206e-4e40-865f-cb58a4086967)

**Comment by geocine** [comment]
I notice it fixes itself after I change the window focus 

![devenv_B1zkXIfavB](https://github.com/DevToys-app/DevToys/assets/507464/f600dee8-f55e-43b7-8a33-a7d695330e61)

**Comment by Dessyreqt** [comment]
Unfortunately changing window focus doesn't do anything for me.

**Comment by veler** [comment]
Duplicate with #1191
