### ISSUE TITLE
[MacOS] Paste Shortcut is not working

### ISSUE THREAD

**Issue by ssrahul96** [DevToys-app/DevToys#1203]
### Current behavior

`CMD` + `V` is not working

Error from logs
```
2024-06-12T08:05:51.0668720+05:30	Warning	[DevToys.MacOS.Core.Clipboard]	[LogGetClipboardFailed]	Failed to retrieve the clipboard data.
AppKit Consistency error: you are calling a method that can only be invoked from the UI thread.
AppKit.AppKitThreadAccessException: AppKit Consistency error: you are calling a method that can only be invoked from the UI thread.
   at AppKit.NSApplication.EnsureUIThread() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/AppKit/NSApplication.cs:line 127
   at AppKit.NSPasteboard.get_GeneralPasteboard() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/macos/generated-sources/AppKit/NSPasteboard.g.cs:line 446
   at DevToys.MacOS.Core.Clipboard.GetClipboardDataAsync() in /Users/etiennebaudoux/RiderProjects/Publish/submodules/DevToys/src/app/dev/platforms/desktop/DevToys.MacOS/Core/Clipboard.cs:line 26
```

### How to reproduce it (as minimally and precisely as possible)

- Open `JSON Formatter` 
- Copy any JSON
- Press `CMD` + `V`

### Expected behavior

Pressing `CMD` + `V` should paste the copied content

### Affected platforms

macOS

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.1

### Relevant Assets/Logs

[log-20240612T080549.txt](https://github.com/user-attachments/files/15797451/log-20240612T080549.txt)

**Comment by ssrahul96** [comment]
@veler , There are no error printed in logs, But still the shortcut `cmd` + `v` is not working,

**Comment by veler** [comment]
Hi @ssrahul96 ,

I did a change that was supposed to help with the problem. Can you please update DevToys to the latest version (2.0.3.0) and share the logs again? The message may be different than the original one.

Thanks

**Comment by ssrahul96** [comment]
version is 2.0.3.0 ly i suppose, today i ve updated it 
<img width="375" alt="image" src="https://github.com/DevToys-app/DevToys/assets/15570570/5c92fc7f-04a6-4771-9f02-aee5b47e576d">


logs : [log-20240625T105016.txt](https://github.com/user-attachments/files/15965087/log-20240625T105016.txt)

**Comment by veler** [comment]
Thanks! I do see an error in the logs, but it's unrelated to the paste command. Does the `Paste` button work?
![image](https://github.com/DevToys-app/DevToys/assets/3747805/cfdc0ada-c39d-4419-8b20-fd9e7a6e0310)

**Comment by ssrahul96** [comment]
yes, the error is irrelevant, 

The `paste` button is working fine.

**Comment by joshradics** [comment]
Updated to the newest version and still getting the same issue too. On OSX ARM64 installed with homebrew. The behaviour is inconsistent too - sometimes I can use the text fields, sometimes I cannot. `CMD + V` doesn't seem to work in any case. Log file attached in case it's useful, but it doesn't seem to trigger any errors when doing this.

[log-20240628T103751.txt](https://github.com/user-attachments/files/16022541/log-20240628T103751.txt)

**Comment by bxb100** [comment]
hi there, DevToys version `2.0-preview.4` support situation: 
- [x] `cmd+a` select all
- [ ] `cmd+x` cut
- [ ] `cmd+c` copy
- [ ] `cmd+v` paste

**Comment by bxb100** [comment]
Hi @veler, could you ship a minor version if you're not busy? We are looking forward to using it.

**Comment by veler** [comment]
> Hi @veler, could you ship a minor version if you're not busy? We are looking forward to using it.

Hi,
This is in progress :D https://github.com/Homebrew/homebrew-cask/pull/181755
