### ISSUE TITLE
Json to Query(SELECT)

### ISSUE THREAD

**Issue by ToanNM27** [DevToys-app/DevToys#1207]
### What feature or new tool do you think should be added to DevToys?

Because I manual copy field by field from json to sql query

### Why do you think this is needed?

A feature will convert json data to query (SQL,...) in SELECT to I can quick query in DB

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
