### ISSUE TITLE
Color Blindness Simulator page is not responsive (MacOS)

### ISSUE THREAD

**Issue by Eliott-B** [DevToys-app/DevToys#1208]
### Current behavior

Images superimposed on MacOs

### Expected behavior

I think we need to have a scrollbar to see the other images

### Screenshots

<img width="822" alt="Screenshot 2024-06-12 at 09 06 01" src="https://github.com/DevToys-app/DevToys/assets/45932754/6e17a935-ea3b-40eb-a806-44724d0cb852">

### Affected platforms

macOS

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.1

**Comment by veler** [comment]
Fixed in #1432
