### ISSUE TITLE
Password generates passwords consisting of one character that i excluded

### ISSUE THREAD

**Issue by isepise** [DevToys-app/DevToys#1213]
### Current behavior

Password generator. 

Settings: 

- Length: 25
- Lowercase: On
- Uppercase: On
- Digits: On
- Special chars: On
- Excluded chars: ^,$

Generated 10 passwords. Output was:

```
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$
```

### How to reproduce it (as minimally and precisely as possible)

Exclude multiple chars starting with the char "^"
Example: ^,$
Hit generate .. the password consists of chars only, that match a char in the exclude list, it seems.

### Expected behavior

Generate passwords according to settings AND exclude the chars that i entered in the textbox fpr excluded chars (separated by colon ",")

### Screenshots

![Screenshot 2024-06-12 163119](https://github.com/DevToys-app/DevToys/assets/17331938/c17bd85c-c3ea-4532-a5c2-75a3d08b1ef4)

### Workaround

Dont enter the char "^" as first char in the exclude list textbox

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.14.0

**Comment by veler** [comment]
Verified and it's fixed in DevToys 2.0, which is available here: https://devtoys.app/download
