### ISSUE TITLE
Dropdown list extends off-screen in Language Settings

### ISSUE THREAD

**Issue by EwdErna** [DevToys-app/DevToys#1217]
### Current behavior

When opening the dropdown list in Settings > Appearance > Language, the list extends off the screen, making the top choices unclickable.

### How to reproduce it (as minimally and precisely as possible)

1. Open DevToys on Windows.
1. Navigate to Settings.
1. Go to Appearance.
1. Open the Language dropdown list.

### Expected behavior

The dropdown list should be fully visible on the screen, allowing all choices to be clickable.

### Screenshots

![image](https://github.com/DevToys-app/DevToys/assets/44013967/9c9fdc56-d9a9-4066-bb46-68af0d5f8fb0)

### Workaround

You can use the arrow keys to select the invisible options.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.1

**Comment by veler** [comment]
Hi,
Thanks for reporting this issue. Note to myself: there are 2 ways to address this issue:
1. Ensure the flyout moves to fit to the window space (that's what VS Code does).
2. Replace this whole flyout by a native context menu on top of the Web View (harder to implement)

**Comment by niyari** [comment]
memo: Consider the window title area.
https://github.com/DevToys-app/DevToys/blob/211c66f4f17fb417ed3d71e58853d2d41fde8913/src/app/dev/DevToys.Blazor/Assets/javascript/popover.ts#L237C118-L237C126

**Comment by veler** [comment]
Fixed in #1425
