### ISSUE TITLE
More Converters csv2json, json2csharp, xml2charp, etc.

### ISSUE THREAD

**Issue by agravity-philipp** [DevToys-app/DevToys#1220]
### What feature or new tool do you think should be added to DevToys?

I want to have more convers like these:
https://json2csharp.com/code-converters/xml-to-csharp

### Why do you think this is needed?

Because I need them and there are a lot of them on the internet. And I want to have it in my "army knife".

### Solution/Idea

Auto-Detect would be nice. So I just have to set the format I want to have it converted. 
A big textbox on the left and a big textbox on the right. Above there is a dropdown of supported languages.

**Comment by cloudfy** [comment]
We've added https://www.nuget.org/packages/DevToys.JsonToCsharp initial release 1.0.5 to DevToys 2.0.1. Happy to take feature requests and more inputs.

**Comment by veler** [comment]
> We've added https://www.nuget.org/packages/DevToys.JsonToCsharp initial release 1.0.5 to DevToys 2.0.1. Happy to take feature requests and more inputs.

Hi @cloudfy , this is awesome! I tested it and it works great so far !

![image](https://github.com/DevToys-app/DevToys/assets/3747805/f7755b10-c670-44fd-862a-98aeec56d1f6)

# One advice:
You can colorize the JSON and C# text automatically by using the `Language` method on the `MultilineTextInput`.

Example:
```csharp
MultiLineTextInput()
                        .Title("JSON editor")
                        .Language("json");
```

This will colorize the code like this:

![image](https://github.com/DevToys-app/DevToys/assets/3747805/8f7c3f41-5fc8-4b70-b803-db719f1a95e9)

**Comment by cloudfy** [comment]
Amazing, added to 1.0.7. Just released :) - you may close the topic.

**Comment by veler** [comment]
Awesome! Thanks !
Well, this topic mentions other things than Json to C#, but I see your point.

By the way, how about supporting Smart Detection in your tool? https://devtoys.app/doc/articles/extension-development/guidelines/UX/support-smart-detection.html

**Comment by veler** [comment]
Closing as some of these scenarios are supported through extensions and we don't plan to support it ourselves (third party extensions are here for this purpose).
