### ISSUE TITLE
ISO 8601 Support In Date Converter

### ISSUE THREAD

**Issue by mbursill** [DevToys-app/DevToys#1229]
### What feature or new tool do you think should be added to DevToys?

I'd really like to see an additional ISO 8601 line added to the date input, where editing that updated the individual date fields, or editing the individual date fields updated the ISO 8601.

![image](https://github.com/DevToys-app/DevToys/assets/2087146/2355db61-53bb-49bf-842f-6853ae72867d)

### Why do you think this is needed?

As web developer I work in ISO 8601 far more than Unix style dates.

**Comment by oliver-sturrock** [comment]
+1

**Comment by yui10** [comment]
![image](https://github.com/DevToys-app/DevToys/assets/79691301/29d0c458-457f-4c44-9535-593415f01595)
