### ISSUE TITLE
Disable Windows 10 theme color usage

### ISSUE THREAD

**Issue by PhilJbt** [DevToys-app/DevToys#1231]
### What improvement do you think would an existing feature or tool in DevToys?

Since I updated from version `1.0.40` to `2.0-preview.1`, reading has become difficult due to the use of my Windows 10 theme color.

![devtools](https://github.com/DevToys-app/DevToys/assets/22506952/89e337bc-767e-481c-98bd-12d06ae97649)

### Solution/Idea

Add an option in the settings to override the Windows theme color with a default dark mode color, or specify the using of the old Devtools dark mode.

**Comment by veler** [comment]
duplicate with #1191
