### ISSUE TITLE
Bug in DevToys extension documentation

### ISSUE THREAD

**Issue by cloudfy** [DevToys-app/DevToys#1232]
### Current behavior

<img width="400" alt="image" src="https://github.com/DevToys-app/DevToys/assets/31371919/4cc6a8a3-419d-4be2-9c35-a61936e6e22f">

at https://devtoys.app/doc/articles/extension-development/getting-started/create-an-extension.html?tabs=vs

LongDisplayTtite should be LongDisplayTitle

### How to reproduce it (as minimally and precisely as possible)

Got to https://devtoys.app/doc/articles/extension-development/getting-started/create-an-extension.html?tabs=vs

### Expected behavior

Correct spelling

### Screenshots

<img width="400" alt="image" src="https://github.com/DevToys-app/DevToys/assets/31371919/4cc6a8a3-419d-4be2-9c35-a61936e6e22f">

### Workaround

None

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version: 2.0.0.preview

**Comment by veler** [comment]
Thanks for finding this! I just updated the documentation to fix it :-)
