### ISSUE TITLE
Blank screen on Ubuntu 22.04

### ISSUE THREAD

**Issue by franksl** [DevToys-app/DevToys#1234]
### Current behavior

Hi,
I'm trying to run the app on an Ubuntu 22.04 machine with i3wm a swindow manager.
When launching the application I get a full white screen with no possible interactions apart from the right click menu.
This happens with both the portable and .deb versions.
With both versions I had to install libwebkitgtk.6.0-4 to be able to launch it.
Thanks,
Frank

### Expected behavior

Having the app visible to be able to interaact with.

### Affected platforms

Linux

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

latest

**Comment by dzr-gregory** [comment]
The same issue with Linux Mint 21.3
`
gbalashov@lm21-vm:~/Downloads$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy
gbalashov@lm21-vm:~/Downloads$ dpkg -l|grep "window manager"
ii  libkf5windowsystem-data                    5.92.0-0ubuntu1                            all          Convenience access to certain properties and features of the window manager
ii  libkf5windowsystem5:amd64                  5.92.0-0ubuntu1                            amd64        Convenience access to certain properties and features of the window manager
ii  libmetacity3:amd64                         1:3.44.0-1ubuntu1                          amd64        library for the Metacity window manager
ii  metacity                                   1:3.44.0-1ubuntu1                          amd64        lightweight GTK window manager
ii  metacity-common                            1:3.44.0-1ubuntu1                          all          shared files for the Metacity window manager

`

**Comment by veler** [comment]
Hello,
I wonder if it has to do with your graphic card. I'm mainly working on virtual machine and started to hit this issue. Disabling hardware acceleration in WebKit solved the issue. I have a fix available here: https://github.com/DevToys-app/DevToys/pull/1259

**Comment by dzr-gregory** [comment]
> Hello, I wonder if it has to do with your graphic card. I'm mainly working on virtual machine and started to hit this issue. Disabling hardware acceleration in WebKit solved the issue. I have a fix available here: #1259

Yes, I'm working on VM using VMWare Workstation. I checked Windows version of DevToys-app on my host machine (Windows 11), and it works fine.

**Comment by veler** [comment]
Hi,
I published a new update of DevToys. Please try it out and let me know if the problem still reproduce. Thanks :)

**Comment by dzr-gregory** [comment]
Yep, now it works fine, thank you @veler !
![image](https://github.com/DevToys-app/DevToys/assets/756853/bf6752eb-3c4b-45f0-afef-44cf404f25a6)

**Comment by openmindead** [comment]
Unfortunately the issue still persists on Arch Linux atm.

**Comment by csmaniottojr** [comment]
I'm experiecing the same error.

I installed the .deb version in the website

 cat /etc/os-release 
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy

**Comment by openmindead** [comment]
Yeah Zorin (based on Ubuntu 22.04) is also affected.
