### ISSUE TITLE
Custom color theme support

### ISSUE THREAD

**Issue by uncenter** [DevToys-app/DevToys#1244]
### What feature or new tool do you think should be added to DevToys?

Support to change the colors of the UI of DevToys.

### Why do you think this is needed?

Many people prefer their own color themes, for syntax highlighting and editor windows, etc. Would be nice to be able to customize the colors of the interface of DevToys too!

### Solution/Idea

Themes could be contributed to this repository directly, or DevToys could have the ability to load external theme files (JSON maybe).

**Comment by veler** [comment]
Not planned for now, sorry. Let's reopen it if there are more upvotes in the future.
