### ISSUE TITLE
Barcode generator

### ISSUE THREAD

**Issue by developing-off** [DevToys-app/DevToys#1249]
### What feature or new tool do you think should be added to DevToys?

the barcode/qrcode generator in this application to make easily and share link / code or develop a systeme where we need to scan codebar etc

### Why do you think this is needed?

i develop some application in c# .net framework and i need some barcodes to test my application so i need to create codebarre and to go on edge and search code bar generator is not fast

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
