### ISSUE TITLE
DevToys 2.0 Preview UI bug: title bar overlapping with app name and "Back button"

### ISSUE THREAD

**Issue by TrangOul** [DevToys-app/DevToys#1251]
### Current behavior

When focused (light and dark Windows modes respectively):

![image](https://github.com/DevToys-app/DevToys/assets/5629046/a4294add-2d01-46f3-af6c-f93e73190d60)
![image](https://github.com/DevToys-app/DevToys/assets/5629046/a44c7d83-81e5-46a6-880c-e660da54f249)

When not focused:

![image](https://github.com/DevToys-app/DevToys/assets/5629046/68d4c65e-8bf8-49bc-909e-5d1ad6d2d5c8)
![image](https://github.com/DevToys-app/DevToys/assets/5629046/1765b9e1-4270-49f7-9b84-a1b6d275e6e4)

This is only an UI issue - the "Back" button is working, even if the upper part, overlapping with the title bar, is clicked 

### How to reproduce it (as minimally and precisely as possible)

OS: Windows 11.

1. Enable the "Show accent color on title bars and windows borders" option in Settings -> Personalization -> Colors.
2. Open DevToys 2.0 Preview.
3. Look at the top left corner of the app. Focus and unfocus the app to see the difference.

### Expected behavior

App name "DevToys" slightly upper, entirely on the title bar.

"Back" ( [<-] ) button slightly lower, entirely below the title bar. It can be moved down, but it would require moving the "Menu" button ( [≡] ) and the menu itself down too.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.2

**Comment by veler** [comment]
Duplicate with #1228
