### ISSUE TITLE
DevToys 2.0 Preview: JSON Formatter does not change indent guides to match the indentation.

### ISSUE THREAD

**Issue by TrangOul** [DevToys-app/DevToys#1252]
### Current behavior

JSON Formatter remember the indentation used on previous app usages, and it can be changed. The indentation guides (those semi-transparent vertical lines in indented lines), however, stay to match the previous session's indentation and cannot be changed.

### How to reproduce it (as minimally and precisely as possible)

1. Launch DevToys.
2. Go to JSON Formatter and paste a (nested) JSON.
3. Set the indentation to `x` spaces.
4. Relaunch DevToys.
5. Go to JSON Formatter and paste a (nested) JSON.
6. Change the indentation from `x` spaces to `y` spaces.
7. Indentation lines are not changed.

If 1 tab or "minified" is used initially instead of `x` spaces, it has the same effect as 4 tabs, also broken if changed to 2 tabs.

### Expected behavior

Indentation guide lines change with the indentation.

### Screenshots

4 spaces initially, changed to 2 spaces.
![image](https://github.com/DevToys-app/DevToys/assets/5629046/5e30e205-07a3-4682-816f-a1e0bfc170d2)

2 spaces initially, changed to 4 spaces.
![image](https://github.com/DevToys-app/DevToys/assets/5629046/1472558c-3109-46c5-bbea-b3b5d63048ba)

### Workaround

Select the desired indentation and restart DevToys.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.2

**Comment by veler** [comment]
Duplicate with #837
