### ISSUE TITLE
DevToys 2.x: Hope to add simplified chinese  support

### ISSUE THREAD

**Issue by joerulau** [DevToys-app/DevToys#1254]
### What feature or new tool do you think should be added to DevToys?

Thank you to the developers. I really like this app. I found that the 1.x version supported Simplified Chinese, but the 2.x beta version no longer supports it. I hope that Simplified Chinese will continue to be supported in future versions.

<img width="600" alt="image" src="https://github.com/DevToys-app/DevToys/assets/8346983/0770bb69-dc94-4491-819b-b074f667b61e">

### Why do you think this is needed?

can allow me to use this app more comfortably

**Comment by veler** [comment]
Hello,
Thanks for your feedback. DevToys is already 100% translated in Chinese simplified and traditional, but there's a bug that made the languages unavailable. I apologies for this inconvenience, as it wasn't on purpose.

![image](https://github.com/DevToys-app/DevToys/assets/3747805/3c1b8ef8-c6ff-4b13-ac84-e75012441678)

I made a fix here:

https://github.com/DevToys-app/DevToys/pull/1255

Thank you :-)

**Comment by joerulau** [comment]
Thank you very much for your response. While using the 2.x beta version on macOS, I've encountered a few issues that negatively affect the user experience. Firstly, the search box is unresponsive and doesn't allow any input. Secondly, each tool has a brief loading process when opened, which, although short, detracts from the overall experience.

https://github.com/DevToys-app/DevToys/assets/8346983/2cdcfb64-a268-44d4-a905-471dde2ab345
