### ISSUE TITLE
winget version not matching with internal version

### ISSUE THREAD

**Issue by masterflitzer** [DevToys-app/DevToys#1257]
### Current behavior

when installing devtoys via winget the version tagged `2.0.2` installs the version `2.0-preview.2`, this results in the same version always being offered as update in winget (infinite upgrade loop when running `winget upgrade`)

the problem is that the package manager version (`2.0.2`) doesn't match with the internal version (`2.0-preview.2`):

- in devtoys > settings > about you can see: `2.0-preview.2`
- in the [DevToys-app.DevToys.installer.yaml](https://github.com/microsoft/winget-pkgs/blob/master/manifests/d/DevToys-app/DevToys/2.0.2/DevToys-app.DevToys.installer.yaml) file you can see: `PackageVersion: 2.0.2`

### How to reproduce it (as minimally and precisely as possible)

powershell:

```pwsh
winget install DevToys-app.DevToys
winget upgrade
# devtoys is always offered as upgrade, so this can be repeated infinitely:
winget upgrade DevToys-app.DevToys
```

### Expected behavior

winget should upgrade to the latest version and then stop offering updates until a new one is released

### Screenshots

notice how version (`2.0-preview.2`) and available (`2.0.2`) columns differ even though the latest version is installed

```
~
❯ winget upgrade
Name                                  Id                  Version       Available
---------------------------------------------------------------------------------
DevToys Preview version 2.0-preview.2 DevToys-app.DevToys 2.0-preview.2 2.0.2
1 upgrades available.
6 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.

~
❯
```

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.2

### Relevant Assets/Logs

relevant github comments:

- https://github.com/microsoft/winget-pkgs/pull/156567#issuecomment-2166560844
- https://github.com/DevToys-app/DevToys/issues/641#issuecomment-2168548971
- https://github.com/DevToys-app/DevToys/issues/641#issuecomment-2168585363

**Comment by veler** [comment]
Hi @stephengillie,
I hope it's OK to ping you here. I'm wondering if you have any recommendation on what to do with such issue.
Thank you very much in advance for your help :-)

**Comment by veler** [comment]
> Yes. The error is that the `PackageVersion` is `2.0.1` but should be `2.0-preview.1`.
> 
> * This happened again with `2.0.2` and `2.0-preview.2`. This is because these are the bits that the package manager uses to match repo data with Registry data.
> * In https://github.com/microsoft/winget-pkgs/pull/156567#issuecomment-2166560844, the version in the application was fixed, but this didn't "backpropagate" into the manifest.
> * If the application matches the Registry, then a `DisplayVersion` isn't necessary and the `PackageVersion` should match both.

Thank you very much! I just released an update and opened a PR here: https://github.com/microsoft/winget-pkgs/pull/159727
Hopefully it's well done this time. Please let me know if you find anything wrong. Thank you again for your help, I really appreciate a lot!

**Comment by masterflitzer** [comment]
@veler after the changes it works perfectly now, thank you very much for jumping through all the hoops to make devtoys available on winget, i very much appreciate it
