### ISSUE TITLE
Icons of pinned tool in Windows 11 Start Menu are too small. 

### ISSUE THREAD

**Issue by veler** [DevToys-app/DevToys#127]
**Describe the bug**
In Windows 11, when pinning a DevToys tool to the Start Menu, the icon gets too small.

**To Reproduce**
The issue can be reproduced outside of DevToys itself. It's likely a Windows 11-wide issue.
In Windows 11, it seems like the icon `Square44x44Logo.altform-unplated_targetsize-32` is used in the Start Menu. Unfortunately, we can't define a 32 x 32px icon in the SecondaryTile API. https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/secondary-tiles

![image](https://user-images.githubusercontent.com/3747805/147713435-d38278fe-6c29-41fd-b213-88863d1fce5b.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/3747805/147710300-6571d4bf-7d2f-4145-bd29-3249b369be03.png)

**Comment by morning4coffe-dev** [comment]
I noticed that in the current Windows 11 dev build (10.0.22543.1000) this bug was somewhat resolved. Currently it puts a square behind the icon like this: 
![image](https://user-images.githubusercontent.com/78549750/152681025-dc08efa2-97d3-4260-969f-a1feb59e4a88.png)
