### ISSUE TITLE
Source Code Tools

### ISSUE THREAD

**Issue by nespjin** [DevToys-app/DevToys#1274]
### What feature or new tool do you think should be added to DevToys?

1. Supports source code lines count display.
2. Supports to export source code to DOCX documents. reference to https://github.com/nespjin/CopyrightsApp

### Why do you think this is needed?

In Chinese, application developers need to apply for a copyright certificate. Because a copyright certificate is required when an application is uploaded to the app marketplace. It requires the submission of source code lines and source code documentation.

### Solution/Idea

reference to https://github.com/nespjin/CopyrightsApp

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
