### ISSUE TITLE
Chain actions

### ISSUE THREAD

**Issue by cmdvdev** [DevToys-app/DevToys#1276]
### What feature or new tool do you think should be added to DevToys?

The application can automatically chain actions. You can configure a series of steps to run one after the other.

### Why do you think this is needed?

For example, if you have a JSON with escaped quotes and you want to format it, you need to perform two actions, one to remove the backslashes and another to format the document. I do this repeatedly and I would like to be able to do it in a single step.

For example, passing two JSON objects, formatting them, sorting them, and comparing them, having a chain of actions.

**Comment by veler** [comment]
Hello,
Thank for the suggestion.
You can sort of already do this using Smart Detection from more output text box, by clicking the Light Bulb icon:
![image](https://github.com/DevToys-app/DevToys/assets/3747805/2c9d53da-f30d-4b91-91b8-cadb7a430b72)
