### ISSUE TITLE
Barcode Encoder/Decoder

### ISSUE THREAD

**Issue by chihyanglee** [DevToys-app/DevToys#1281]
### What feature or new tool do you think should be added to DevToys?

I propose adding a barcode encoder/decoder tool to DevToys. This tool would allow users to generate and decode various types of barcodes, similar to the existing QR code encoder/decoder.

### Why do you think this is needed?

This feature is needed to complement the existing QR code tool. Users have requested a barcode generator/decoder, as seen in issue #1149. Barcodes like Code 39 and Code 128 are widely used in many industries, and having this tool would make DevToys more versatile and useful.

**Comment by veler** [comment]
Duplicate with #1249
