### ISSUE TITLE
Add URL Shortner

### ISSUE THREAD

**Issue by vrajjbhatt** [DevToys-app/DevToys#1285]
### What feature or new tool do you think should be added to DevToys?

URL Shortner

### Why do you think this is needed?

It is also essential utility while sharing urls, posting urls among online platforms.

### Solution/Idea

Implementation could be possible similar to bit.ly. In this case shortened url can be msft or something similar.

**Comment by veler** [comment]
Hi,
This would require an internet connection, which goes outside of the philosophy of DevToys base app. But this could be done in an extension.
