### ISSUE TITLE
cannot paste in mac app with cmd+v

### ISSUE THREAD

**Issue by taivu** [DevToys-app/DevToys#1294]
### Current behavior

using json formatter, i cannot use keyboard `cmd+v` to paste. i have to right click paste or click on the paste icon.

### Expected behavior

paste into input.

### Affected platforms

macOS

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.3

**Comment by veler** [comment]
Duplicate with #1203
