### ISSUE TITLE
Screen Coords Finder

### ISSUE THREAD

**Issue by JuaanP** [DevToys-app/DevToys#1298]
### What feature or new tool do you think should be added to DevToys?

Find screen pixel coordinates on the current cursor position

### Why do you think this is needed?

sometimes when developing an automated software you need to locate coordinates on the screen, this feature would be helpful for these situations

**Comment by jerone** [comment]
You could use PowerToys (from Microsoft) for this feature:
https://learn.microsoft.com/en-us/windows/powertoys/screen-ruler

**Comment by JuaanP** [comment]
thanks, didn't try screen ruler
