### ISSUE TITLE
New MS store icon looks off

### ISSUE THREAD

**Issue by amweiss** [DevToys-app/DevToys#1311]
### Current behavior

The new MS store icon looks possibly too small but also has a strange background to it. I did a reboot after install to make sure it wasn't just icon caching or something.

![image](https://github.com/user-attachments/assets/e99cb8a9-014d-48ce-9816-36744ae5f21b)
![image](https://github.com/user-attachments/assets/e721bc7c-fc79-444d-9987-21a425f8d3ce)

### How to reproduce it (as minimally and precisely as possible)

1. Install DevToys-Preview from MS Store
2. Notice the icon seems too small and has a strange background

### Expected behavior

1. The DevToys-Preview icon is roughly the same size as Windows Terminal
2. The DevToys-Preview icon has a transparent background

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.4

**Comment by veler** [comment]
Hi,
Thanks for reporting this issue. This is frustrating because it's been some time I'm trying to address it. When testing locally, the icon is much better, but once published, it is not, and I don't understand why yet.

**Comment by amweiss** [comment]
I completely understand, this kind of thing drives me nuts when trying to make icons consistent across app stores and installs. I haven't done an MS store icon since Windows 8 monochrome tiles were used but let me know if additional testing could help.

**Comment by veler** [comment]
Reopening.... I don't get it... It was working. Once merged, it doesn't work anymore...

**Comment by veler** [comment]
Alright, got it fix again here: https://github.com/DevToys-app/DevToys/commit/6b5f92b924c0ecf808700a6411c444bb7fc49ee2
This time it worked once pushed to Github.
