### ISSUE TITLE
ASCII art generator

### ISSUE THREAD

**Issue by istrasci** [DevToys-app/DevToys#1312]
### What feature or new tool do you think should be added to DevToys?

Just installed DevToys, and so far it's really great.

I'd love to see a feature-rich ASCII Art generator included.  As a developer, sometimes I want to make bigger, "banners" of text that stand out in code comments, documentation, etc.  Sometimes I also use it to make text-only emails look a little nicer.  It would be nice to input regular text or an image an generate the ASCII art.

#### Text
*  https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
* https://www.asciiart.eu/text-to-ascii-art

#### Image
* https://www.asciiart.eu/image-to-ascii
* https://www.ascii-art-generator.org/
* https://ascii-generator.site/

### Why do you think this is needed?

ASCII Art can often be useful in code comments/documentation, text-only emails, etc.

**Comment by ghatolow** [comment]
DXL STEALER

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
