### ISSUE TITLE
Window opens offscreen and I can't move it

### ISSUE THREAD

**Issue by hahn-kev** [DevToys-app/DevToys#1315]
### Current behavior

I'm not sure what happened, but when I launch the tools the window doesn't show up, I can see the taskbar icon, and when I hover it I see a preview of the window, but the window never shows on my desktop. I can click on it but nothing happens, it's like it's off screen. I use multiple monitors and frequently switch between multiple configurations.

### How to reproduce it (as minimally and precisely as possible)

Launch the program. I don't know what I did to get into this state though.

### Expected behavior

It should open and not be off screen.

### Workaround

Things I tried:
- win+arrow hotkeys to move windows
- right click preview to access tool tip to move the window, no tooltip shows up for dev toys, unlike other programs
- win + tab, the window shows up with a full preview, but clicking on it and the right click options don't work.
it may be possible with some custom tools to move the window back to my desktop, but I'm not willing to install some tools or write an autohotkey script to find out.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

version 2.0.4.0 from windows installed app settings

**Comment by veler** [comment]
Hi,
Thanks for reporting this issue. I've been able to reproduce it and have a fix: https://github.com/DevToys-app/DevToys/pull/1321
