### ISSUE TITLE
Add Georgian language on Crowdin

### ISSUE THREAD

**Issue by giosal** [DevToys-app/DevToys#1316]
### What feature or new tool do you think should be added to DevToys?

I would like to request adding a Georgian language on Crowdin so that I can translate it.
I have also requested this in Discussions on Crowdin, but given that other topics have no replies for up to a year and the languages were not added, I thought I would also duplicate it here.

### Why do you think this is needed?

While there's less than 10 million people speaking Georgian language, the Georgian developer society is growing exponentially, especially after COVID and it would be greatly appreciated if the DevToys is available in Georgian language.

**Comment by veler** [comment]
Hi,
Thanks for the suggestion. I just added it here: https://crowdin.com/project/devtoys/ka
