### ISSUE TITLE
JSON Tree Browser

### ISSUE THREAD

**Issue by paulmdavies** [DevToys-app/DevToys#1319]
### What feature or new tool do you think should be added to DevToys?

A JSON tree browser, as in [this website](https://jsonviewer.stack.hu/)

### Why do you think this is needed?

It makes large JSON files easier to read than the existing formatter.

### Solution/Idea

See [this website](https://jsonviewer.stack.hu/)

### Comments

![image](https://github.com/user-attachments/assets/6fd9c0dd-29f1-4e63-8c03-c381baf67ba4)

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
