### ISSUE TITLE
File splitter

### ISSUE THREAD

**Issue by cmdvdev** [DevToys-app/DevToys#1325]
### Current behavior

when you select split in files with 100 lines, the current output has 1024

![imagen](https://github.com/user-attachments/assets/8d162876-d1f4-4bbf-ac7d-18d73e3708d4)

### Expected behavior

Files with the number of files selected

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0.4.0 preview

**Comment by veler** [comment]
Hi,
File Splitter is a third party extension. I do not own or maintain it. Please move this issue to https://github.com/adensW/DevToysExtensions
Thanks
