### ISSUE TITLE
File spliter can choose if you want to maintain headers

### ISSUE THREAD

**Issue by cmdvdev** [DevToys-app/DevToys#1326]
### What feature or new tool do you think should be added to DevToys?

In file splitter (great tool) maybe yo can choose if you want to maintain headers in all files, maybe is usefull for csv files

### Why do you think this is needed?

If you nedd to split a file and the file is a common csv, yo probably need headers too in each file

**Comment by veler** [comment]
Hi,
File Splitter is a third party extension. I do not own or maintain it. Please move this issue to https://github.com/adensW/DevToysExtensions
Thanks
