### ISSUE TITLE
Programming language converter

### ISSUE THREAD

**Issue by theuserbl** [DevToys-app/DevToys#1327]
### What improvement do you think would an existing feature or tool in DevToys?

I think a programming language converter like the converters of Tangible Software would be nice, to convert code from one language to an other language
https://www.tangiblesoftwaresolutions.com/

### Solution/Idea

A library for converting code between C# and VB.NET existing at
https://github.com/icsharpcode/CodeConverter
or
https://github.com/paul1956/CSharpToVB

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
