### ISSUE TITLE
JSON analyzer tool

### ISSUE THREAD

**Issue by IncrediblePony** [DevToys-app/DevToys#1332]
### What feature or new tool do you think should be added to DevToys?

A great addition would be a JSON analyzer tool where you could paste some JSON into a text field and show a searchable structure in which you could collapse/expand objects and mark values for comparison.

inspiration: https://jsonviewer.stack.hu/ but better

### Why do you think this is needed?

I deal a lot with 3rd party REST APIs and their responses can be, confusing/long winded, to say the least. It would be awesome to have a tool in my toolkit to analyze JSON better.

### Solution/Idea

![image](https://github.com/user-attachments/assets/d5ed1ebd-2d52-4093-87ad-9e10b0e1569e)

A very crude mock-up but should outline the general idea. Have a JSON input. Have a JSON viewer with collapsible/expandable objects. Possible to highlight multiple values for comparison in separate window.

**Comment by tonixx** [comment]
Love the idea! Someone should build this (maybe with the help of AI)

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
