### ISSUE TITLE
Please fix frame rate drops

### ISSUE THREAD

**Issue by tanyaofei** [DevToys-app/DevToys#1337]
### Current behavior

I just upgraded from version 1.x to version 2.x. My first impression is that it has become very slow, with noticeable frame drops during scrolling, even though I am currently using an M3 Max processor. Could you optimize the GUI to ensure it runs at least at 60 fps?

### Expected behavior

Pleasy ensure it runs at least at 60 fps.

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version: 2.0-preview.4 | OS: MacOS Apple SiliCon

**Comment by SaifAqqad** [comment]
I tried it on both Windows and Linux mint (on the same hardware) and I can confirm it runs really slow on linux (dropping frames when switching tools, scrolling long text, etc)

**Comment by Anti-Apple4life** [comment]
Same here on Arch Linux (btw)

**Comment by veler** [comment]
Duplicate with #1269
