### ISSUE TITLE
Topmost item in Lorem lpsum generator text corpus list has a very narrow mouse reaction area and overlaps with the title bar

### ISSUE THREAD

**Issue by pujfei** [DevToys-app/DevToys#1340]
### Current behavior

![image](https://github.com/user-attachments/assets/3c4e731a-1320-47b1-b7cc-9fe81700d38d)
![image](https://github.com/user-attachments/assets/d2d559c0-a429-4112-a5d1-9bdc466c6692)
![image](https://github.com/user-attachments/assets/b0862707-fc62-4d30-862c-ed3e19a1c5e6)
![image](https://github.com/user-attachments/assets/8855bd6b-b71e-4268-96a3-590a04eb2cfb)

### How to reproduce it (as minimally and precisely as possible)

Go to Lorem lpsum generator, click text corpus, navigating to the top items in the list, observe the item's reaction to mouse movement.

### Expected behavior

1. the topmost item**s** should have the same mouse-on reverse highlight action, just like other items.
2. the pop-up list should always top the app, which means holding the focus even when the mouse moves to the title bar area of the app, no overlapping.
3. all display language GUI should be taken into consideration, i have tried the en-us and zh-cn languages, problems exist under both.
4. this is a report from WIndows 10 platform, no idea what happens in a Linux and MacOS one, please give it a try, probably the same problem.
5. new discovery, same problem happen in "settings - language" too, i'm afraid you have to investigate into all pop-up selection box in this app.

### Screenshots

see above

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.4, OS version: Windows 10 Pro, 22H2, 19045.4717

**Comment by veler** [comment]
Hello,
Thank you, I made a fix :)
