### ISSUE TITLE
latest version crash on Windows 11 when is opened.

### ISSUE THREAD

**Issue by nestg** [DevToys-app/DevToys#1342]
### Current behavior

latest version v2.0.4.0 crash on Windows 11 when is opened.

### Expected behavior

Crash when is opened.

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

v2.0.4.0

**Comment by veler** [comment]
Hi,
I need more description to understand why it is happening. Does the app not open at all? Does it crash after open a file? Anything else? Sharing the logs may help too.

**Comment by veler** [comment]
Closing due to lack of info
