### ISSUE TITLE
Unable to select copy with cursor

### ISSUE THREAD

**Issue by ShaPoHun** [DevToys-app/DevToys#1344]
### Current behavior

Unable to select copy with cursor

### How to reproduce it (as minimally and precisely as possible)

json formatting
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/1249ac6f-0299-44d7-a99a-3cf4a3265e71">

### Expected behavior

Can in the output box, select Copy

### Affected platforms

macOS

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

 v2.0.4.0

**Comment by veler** [comment]
Hi,
This is recently fixed but not published yet. Marking as duplicate with https://github.com/DevToys-app/DevToys/issues/1203#issuecomment-2241048592

**Comment by zhan3333** [comment]
Version: 2.0-preview.5

Same probleam, I can't select text and copy in JWT Decoder, and I can't enlarge the header, payload window, even though it's blank underneath.
<img width="1328" alt="image" src="https://github.com/user-attachments/assets/7b60398f-3a56-4e1c-914c-4f9ffa5e317a">
