### ISSUE TITLE
Text Escape Uses Wrong Code For Line Break (\r instead of \n)

### ISSUE THREAD

**Issue by stimpy77** [DevToys-app/DevToys#1356]
### Current behavior

Line breaks are getting encoded with \r

### How to reproduce it (as minimally and precisely as possible)

Formatted JSON with line breaks, pasted into Text Encoder 

### Expected behavior

Line breaks should be encoded with \n.

When encoding line breaks on Windows, it should encode with either \r\n or else \n. Not with \r. 
The \r is the extraneous carriage return ("r" for carriage _r_ eturn) that MS-DOS had and carried over into Windows, whereas UNIX systems only did line break ("n" for "newline"); for JSON and web etc, Windows apps always handle \n correctly but neither UNIX nor Windows would guarantee a line break with a carriage return ("\r").

### Screenshots

![image](https://github.com/user-attachments/assets/63e28272-a7f7-44ec-ab0a-1a61fdc9e21a)

### Workaround

Copy Output to clipboard, paste into Notepad, find and replace "\r" with "\n".

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.14

**Comment by veler** [comment]
Hi,
This issue has been resolved in DevToys 2.0, which is currently in preview: https://devtoys.app/blog/announcing-devtoys-2.0-preview
You can download it here: https://devtoys.app/download

Duplicated with #468
