### ISSUE TITLE
latest version 1.0.13.0 crash on Windows 11 when is opened.

### ISSUE THREAD

**Issue by PublicCode1337** [DevToys-app/DevToys#1357]
### Current behavior

When i open this program crash this instandly

[Bug Report.mp4](https://github.com/user-attachments/assets/4d90a3f2-7cd2-443d-bfbb-4ad8acdf71fe)

### Expected behavior

its crash instand on start

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.13.0

### Relevant Assets/Logs

[log-20240801T230901.txt](https://github.com/user-attachments/files/16461971/log-20240801T230901.txt)

**Comment by veler** [comment]
Hi,
It looks like you're trying to run devtoys 2.0, not 1.0.
Did you uninstall Microsoft Edge and/or the Edge Webview?

**Comment by veler** [comment]
Closing as lack of information and follow-up.
