### ISSUE TITLE
Add a "Now" button for the Date Converter

### ISSUE THREAD

**Issue by dev-michael-schmidt** [DevToys-app/DevToys#1358]
### What feature or new tool do you think should be added to DevToys?

For the Date Convert: A button that says "Now" with a stopwatch icon.  You click the "Now" button and right this very instant:

- The "Date" box gives the current Linux Epoch in seconds
- The ISO 8601 textbox gives the full date, time

Bonus points: a "track" button that updates in real-time

### Why do you think this is needed?

It is time-consuming to enter the current hour, minute, and second (and sometimes days such as Feb 29th) manually for an ever-changing value.

Imagine how frustrating it would be for cases when all you want is a time that happened at least 2 minutes ago.

### Solution/Idea

I would find a way to grab the current Epoch.  With this Epoch, it would populate the fields.

Programmatically, you would use a sys call for the current epoch when the button is clicked or an "on-down event."  If the Date and ISO 8601 boxes are tightly coupled, it might be as simple as setting this epoch in the "Date" box

**Comment by JakeS-dot** [comment]
Hi! I know this comment is late but - I made this as a pr around 20 days ago. If you really want this, feel free to run it locally!
