### ISSUE TITLE
Word counter and character counter

### ISSUE THREAD

**Issue by odracir** [DevToys-app/DevToys#1359]
### What feature or new tool do you think should be added to DevToys?

Word counter and character counter is a tool that allows you to count the number of words or characters that a text has. You simply have to position the cursor inside the window and start typing with the keyboard. The system will automatically count the number of words and characters you have entered. It is also possible to copy and paste text that you have typed outside the system; It will automatically display the word and character count of the copied text.

Knowing the number of words or characters in a document can be very useful. As an example, if an author is asked for a minimum or maximum number of words allowed to write, the word counter will help them know if their article meets the requirements.

In addition, the word counter automatically shows the ten most used words and their density within the article you are writing. This allows you to know which words you use most frequently and in what percentage you use them within the article. This will help you avoid overusing certain words in a text and will allow you to ensure that the distribution of keywords matches what you are looking to obtain from the text.

The closest idea may be like the example of this web application:: https://www.contadordepalabras.com/

![Untitled-1](https://github.com/user-attachments/assets/89922b8a-5963-42d1-9a6c-3666fe573165)

Thank you very much for your patience and time.

### Why do you think this is needed?

Word count can also be important in defining reading and writing speeds. The word counter will help you determine both. Simply set the timer and start writing. When the time is up, you'll be able to instantly know how many words you've typed during that time period.

**Comment by veler** [comment]
Hi,
It's already available in DevToys 1.0 and 2.0. use the `Analyzer & Utilities` tool.

![image](https://github.com/user-attachments/assets/c99acaa5-9c6c-4a0a-baa0-d1519f440835)
