### ISSUE TITLE
UpperCase/LowerCase/CamelCase/SnakeCase Converter

### ISSUE THREAD

**Issue by thanh-tran-tien** [DevToys-app/DevToys#1361]
### What feature or new tool do you think should be added to DevToys?

As title

### Why do you think this is needed?

Sometime you need to convert between those case i listed like rename file,
Ex; I'm migrating an WPF app to MAUI and all images in there naming as CamelCase  but MAUI resource don't allow that, it must be lowerCase

**Comment by guotie** [comment]
but cannot navigate to this menu by search uppercase or lowercase
