### ISSUE TITLE
String formatter

### ISSUE THREAD

**Issue by lnaie** [DevToys-app/DevToys#1363]
### What feature or new tool do you think should be added to DevToys?

From any to any casing: lower, upper, snake, camel, pascal.

### Why do you think this is needed?

A lot for devs and devops.

**Comment by maartenpeels** [comment]
That's already possible using the text Analyser & Utilities

**Comment by veler** [comment]
Hi,
It's already available in DevToys 1.0 and 2.0. use the Analyzer & Utilities tool.
![image](https://github.com/user-attachments/assets/cd724434-9f1c-4168-84c0-41ea657f90d0)
