### ISSUE TITLE
MAC Address generator

### ISSUE THREAD

**Issue by sstaub** [DevToys-app/DevToys#1367]
### What improvement do you think would an existing feature or tool in DevToys?

A MAC Address generator will helpful.

### Solution/Idea

Like the UUID generator there should a MAC Address generator following RFC 9542. It should possible to generate randomized MAC addresses for local use.

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
