### ISSUE TITLE
Ubuntu 22.04 - bwrap setting up uid map permission denied 

### ISSUE THREAD

**Issue by marcosins** [DevToys-app/DevToys#1373]
### Current behavior

When launching from terminal, DevToys doesn't start.

```bash
$ ./DevToys.Linux --disable-sanboxing
bwrap: setting up uid map: Permission denied
** (DevToys:2648460): ERROR **: 11:57:18.453: Failed to fully launch dbus-proxy: El proceso hijo terminó con el código 1
Abortado (`core' generado)
```
Relevant `journalctl` log:
```bash
$ journalctl -f
(...)
ago 12 12:11:14 lenovo-y540 rtkit-daemon[1784]: Supervising 11 threads of 8 processes of 1 users.
ago 12 12:11:35 lenovo-y540 kernel: audit: type=1400 audit(1723479095.677:169): apparmor="AUDIT" operation="userns_create" class="namespace" info="Userns create - transitioning profile" profile="unconfined" pid=2710574 comm="bwrap" requested="userns_create" target="unprivileged_userns"
ago 12 12:11:35 lenovo-y540 kernel: audit: type=1400 audit(1723479095.678:170): apparmor="DENIED" operation="capable" class="cap" profile="unprivileged_userns" pid=2710577 comm="bwrap" capability=8  capname="setpcap"
ago 12 12:11:35 lenovo-y540 kernel: audit: type=1400 audit(1723479095.678:171): apparmor="DENIED" operation="open" class="file" info="Failed name lookup - disconnected path" error=-13 profile="unprivileged_userns" name="proc/2710577/uid_map" pid=2710577 comm="bwrap" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
(...)
```

### How to reproduce it (as minimally and precisely as possible)

1. Download DevToys 2 from the releases page
2. Run `DevToys.linux` from terminal

### Expected behavior

DevToys should run

### Workaround

Downgrade to Ubuntu 22.04

### Affected platforms

Linux

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0.5.0

**Comment by marcosins** [comment]
Further reading of the issue seems to link to a problem in Ubuntu itself due to a missing AppArmor profile[^1][^2]

[^1]: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844/?comments=all#yui_3_10_3_1_1723478114436_1043
[^2]:containers/bubblewrap/issues/505

**Comment by badcel** [comment]
See #1198.

**Comment by marcosins** [comment]
My bad, feel free to close this as a duplicate 🤦🏻‍♂️

**Comment by Its-Just-Nans** [comment]
Just because this issue is the first one in google result when searching for `bwrap: setting up uid map: Permission denied`, I'm adding some of my findings

```sh
sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```

> From ubuntu blog https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces


<br/>
<br/>
<br/>
<br/>
<br/>

```sh
sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=1
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=1
```

**Comment by marcosins** [comment]
@Its-Just-Nans yours is a system wide solution and downgrades the security of your system. Please prefer the solution linked in #1198 that applies only to `bwrap` which is needed by DevToys.

**Comment by Its-Just-Nans** [comment]
Yes indeed.

This comment was mostly for people who are searching for `bwrap: setting up uid map: Permission denied` in google !
