### ISSUE TITLE
Add a Feature to Remove Duplicates to 'Text Analyzer and Utilities'

### ISSUE THREAD

**Issue by H20-DHMO** [DevToys-app/DevToys#1376]
### What improvement do you think would an existing feature or tool in DevToys?

DevToys can remove any duplicates

### Solution/Idea

Add a "Remove duplicates" feature similar to "Convert line break", "Convert case" and "Sort lines".

### Comments

No response.
I am using a translation tool, so I apologize if the content is incorrect.

**Comment by veler** [comment]
Hi,
I wonder if the `Duplicate Detector` extension for DevToys, made by @Poilaupat, would help.
https://www.nuget.org/packages/DuplicateDetectorExtension

**Comment by H20-DHMO** [comment]
Thank you, veler!

This is exactly the feature I was looking for. 
I hope this functionality will not only remain an extension but also be officially adopted.
Since the feature I wanted now exists, I will close this issue. Thank you!
