### ISSUE TITLE
Add encryption and decryption capabilities

### ISSUE THREAD

**Issue by onedaycodes** [DevToys-app/DevToys#1386]
### What feature or new tool do you think should be added to DevToys?

Hope to add symmetric encryption, such as AES, etc. Asymmetric encryption like RSA for encryption and decryption capabilities. Thank you very much for the author's sharing.

### Why do you think this is needed?

Because frequent encryption and decryption testing and verification need to be conducted.

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
