### ISSUE TITLE
Quoted Printable Decode / Encode

### ISSUE THREAD

**Issue by GZecchiniJ2M** [DevToys-app/DevToys#1390]
### What feature or new tool do you think should be added to DevToys?

It should be a Quoted Printable Decoder/Encoder

### Why do you think this is needed?

Working with emails, it's common to deal with that kind of encoding and it's useful to have an encoder / decoder for it in the tool

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
