### ISSUE TITLE
JWT decode dates tooltip text

### ISSUE THREAD

**Issue by micheivan** [DevToys-app/DevToys#1394]
### What feature or new tool do you think should be added to DevToys?

Add a tooltip to Dates fields in decoded JWT, like jwt.io page.

### Why do you think this is needed?

It's really annoying to take the number and convert it to a specific date.

### Solution/Idea

Tooltip text, or automatic conversion for exp, iat and auth_time claims from decoded jwt.

**Comment by btiteux** [comment]
Hello, what's the version you are using?

In DevToys v2 preview, you have a tool when you hover the value of exp and iat.
You can also click on this icon, and you have a data table.
![image](https://github.com/user-attachments/assets/f4c98704-f5bd-47ab-909d-7709b34687b3)

**Comment by micheivan** [comment]
Hello...
My mistake. 
I was trying with the lamp of transformations.
Thanks for your answer.

**Comment by btiteux** [comment]
No problem. 
The lamp information is more about showing you what tools can be compatible with the content of this input. 

I'm going to close this issue if everything is good.

**Comment by micheivan** [comment]
Yes... close it.Thanks again.

    El martes, 29 de octubre de 2024, 07:11:09 p. m. ART, Benjamin TITEUX ***@***.***> escribió:  
 
 


No problem.
The lamp information is more about showing you what tools can be compatible with the content of this input.

I'm going to close this issue if everything is good.
