### ISSUE TITLE
Sixel Image Encoder / Decoder

### ISSUE THREAD

**Issue by jogo-** [DevToys-app/DevToys#1396]
### What improvement do you think would an existing feature or tool in DevToys?

Add a similar tool as the Base64 Image Encoder / Decoder, but for the [Sixel](https://en.wikipedia.org/wiki/Sixel) bitmap graphics format supported in many terminal emulators including latest [Windows Terminal Preview v1.22.2362.0](https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0)

### Solution/Idea

Using [libsixel](https://github.com/saitoha/libsixel)

**Comment by veler** [comment]
Hi,
This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
