### ISSUE TITLE
JSON formatter is too slow

### ISSUE THREAD

**Issue by ali-safapour** [DevToys-app/DevToys#1397]
### Current behavior

I tried to live edit a JSON structure but the software gets too slow and laggy during the modification.

System specification:
Linux Mint 21.3
Intel i5-10300h
8 GBs of Memory
Nvidia GTX 1650

### Expected behavior

Fluent modification and getting an instant output in the output box.

### Affected platforms

Linux

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0-preview.4

**Comment by veler** [comment]
Hello,
Thanks for this feedback. Would you please be able to share a gif or video that shows how laggy it is? Also, how big is your Json?
Thanks

**Comment by veler** [comment]
Closing as lack of following information
