### ISSUE TITLE
Read the QR code directly from the screen

### ISSUE THREAD

**Issue by yui10** [DevToys-app/DevToys#1402]
### What improvement do you think would an existing feature or tool in DevToys?

Currently, it is possible to read QR codes in images and clipboards.
However, it requires a separate tool to take a screenshot, which is time-consuming.
Therefore, it would be nice to have the ability to take a screenshot and read the QR code from within the application.

### Solution/Idea

Add the ability to take screenshots to the QR Code tool.

### Comments

It would be better if it is possible to capture any area like Snipping Tool.

https://www.microsoft.com/en-us/windows/tips/snipping-tool

**Comment by veler** [comment]
Hi, and thanks for your suggestion.
While this would indeed be handy, we'd need to implement a platform-specific solution for each operating systems, increasing the amount of dependencies and making `DevToys.Tools` harder to maintain. Given the fact we already support Smart Detection (you can just paste the image in the clipboard), I would like not to do this work unless there's a significant amount of upvotes on this issue.
