### ISSUE TITLE
Hercules similar features to test TCP/UDP connections

### ISSUE THREAD

**Issue by saymoncoppi** [DevToys-app/DevToys#1405]
### What improvement do you think would an existing feature or tool in DevToys?

Easy way to test TCP/UDP requests

### Solution/Idea

I use it on windows:
https://www.hw-group.com/product-version/hercules

**Comment by saymoncoppi** [comment]
I mean something similar to Wireshark and Netcat combined.

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
