### ISSUE TITLE
[API] GetChildElementById doesn't work with Card

### ISSUE THREAD

**Issue by jerone** [DevToys-app/DevToys#1406]
### Current behavior

[`GetChildElementById`](https://github.com/DevToys-app/DevToys/blob/20136a6eedfb5270bc9b73cc14d1f97c8b837192/src/app/dev/DevToys.Api/Tool/GUI/Components/UIToolView.cs#L105) is not able to find element for pane children within the `SplitGrid`.

It works for any other child.

### How to reproduce it

```c#
public UIToolView View
{
    get
    {
        return new UIToolView(
            SplitGrid()
              .WithLeftPaneChild(Button("custom-id-1"))
              .WithRightPaneChild(DataGrid("custom-id-2"))
        );
    }
 }
```
```c#
var element1 = Gui.View.GetChildElementById("custom-id-1"); // null
var element2 = Gui.View.GetChildElementById("custom-id-2"); // null
```

### Expected behavior

Expect element with id to be found within `SplitGrid`.

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 2.0-preview.5

**Comment by jerone** [comment]
After some more investigation, it's actually not `SplitGrid` that doesn't work, but `Card` that is not able to iterate through `UIElement` property.

I'm working on a fix.

**Comment by veler** [comment]
Great catch! Thank you for this!
