### ISSUE TITLE
Improve search to include features within a tool

### ISSUE THREAD

**Issue by DanAtkinson** [DevToys-app/DevToys#1409]
### What improvement do you think would an existing feature or tool in DevToys?

As an example, I was looking for a HMAC tool in DevToys but I couldn't find it by searching.
![image](https://github.com/user-attachments/assets/9e85017e-30d8-4915-a394-a88d0795b291)

I was a little surprised such a feature wasn't present and I was about to raise it when I saw #516 which stated that the HMAC feature had been added to the "Hash Generator".

### Solution/Idea

I feel that the search functionality could be improved by also returning results that are a feature _within_ a particular tool rather than the name of the tool itself.

### Comments

For what it's worth, I also searched for "SHA512 for example, and this did return results.
![image](https://github.com/user-attachments/assets/fbb85b5f-bbb2-4f21-ba3b-8ce949170cb9)

Perhaps then, HMAC just needs to be added to the library used by the search feature?

Kind regards
Dan

**Comment by veler** [comment]
Hello,
Thanks for this feedback. This is something to be done per-tool unfortunately. For now though, I added these keywords to the Hash/Checksum tool.
