### ISSUE TITLE
SixLabors.ImageSharp 3.1.4 vulnerable

### ISSUE THREAD

**Issue by jerone** [DevToys-app/DevToys#1410]
### Current behavior

DevToys.Api dependency SixLabors.ImageSharp version 3.1.4 is vulnerable: 

* Severity 1 - https://github.com/advisories/GHSA-qxrv-gp6x-rc23
* Severity 2 - https://github.com/advisories/GHSA-63p8-c4ww-9cg7

### Expected behavior

No vulnerabilities.

### Affected DevToys kind

DevToys (app with GUI), DevToys CLI

### DevToys Version

DevToys.Api.2.0.5-preview

**Comment by jerone** [comment]
Ping @veler for these vulnerabilities.

**Comment by veler** [comment]
Hello,
Sorry for the late answer here and thank you for notifying this issue. I opened a PR to update the dependencies.
