### ISSUE TITLE
Support for watermark

### ISSUE THREAD

**Issue by FPierre** [DevToys-app/DevToys#1415]
### What feature or new tool do you think should be added to DevToys?

The ability to add watermark would be nice 🚀

### Why do you think this is needed?

It is better to keep it local instead of uploading potentially sensitive files in any online solution

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
