### ISSUE TITLE
Docker command-line to docker-compose.yml formatter

### ISSUE THREAD

**Issue by behm** [DevToys-app/DevToys#1418]
### What feature or new tool do you think should be added to DevToys?

Often times I will get a `docker run` command-line for a container image that I would like to try.  Most of the time I prefer to use the `docker compose` command-line along with an assocaited docker-compose.yml file.  It would be great if there was a DevToy that could take a `docker run` command and convert it to a docker-compose.yml format.  If it makes sense, maybe a way to convert it back to command-line but in the event where several services are configured, this might result in several `docker run` commands

### Why do you think this is needed?

This would keep me from needing do a web search for how someone else implemented it using `docker compose`.  It keeps me in DevToys for something that should be a simple format change instead of going to an online tool and needing to submit information to a site.

### Solution/Idea

I see this as a textbox where you can paste in a `docker run` command and the generator displays what that command would like look like in a docker-compose.yml file.  A copy button would allow the user to copy and paste the YAML to where they would like to save the file.

### Comments

Thank you for your consideration of this feature.  DevToys is a great set of tools.

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. This could be a good idea of third-party tool. This can be achieved [with our SDK](https://devtoys.app/doc). Unless there's a strong demand (through upvote) for this tool to be shipped by default with DevToys, I will close this ticket and let anyone who wants making and publish the tool through an extension.
Thanks!
