### ISSUE TITLE
Provide method for viewing/accessing any truncated text

### ISSUE THREAD

**Issue by CatSchneider** [DevToys-app/DevToys#1419]
### What improvement do you think would an existing feature or tool in DevToys?

When attempting to view the descriptions of some of the tools in the tool viewers, most descriptions are short enough that they can be read in the UI without issue. However, there are some that appear to be too long or the title is too long such that the end of the description is truncated. 
![image](https://github.com/user-attachments/assets/82f764e6-f11c-4f0f-80fb-093fc1a3cef1)
Alt: Screenshot of the DevToys app, highlighting the truncated description field of the "Text Escape/Unescape" tool within the Text tools viewer.

The issue is that I cannot find any way to access the entirety of the description. There is OnHover helper text that pops up when hovering over the buttons that appear at the bottom of the tool cards, but none for the description.
![image](https://github.com/user-attachments/assets/f540722c-5d9b-466e-a22c-bd54ada256cc)
Alt: A screenshot showing the "Text Escape/Unescape" tool with the OnHover helper text, "Open in a new window", appearing above the mouse pointer hovered over the New Window button.

### Solution/Idea

Simplest method would be to provide OnHover helper text for any/all areas where text may be truncated.

Another option specifically for tool descriptions would be to provide the full description for the tool just below the title when using the tool.
![image](https://github.com/user-attachments/assets/9f8c6cf6-612d-4d91-b2f3-78bd16449ec8)
Alt: Screenshot of the "Text Escape/Unescape" tool, displaying the tool description below the title.

**Comment by veler** [comment]
Hi,
This was fixed in DevToys 2.0, currently in preview: https://devtoys.app
