### ISSUE TITLE
Subnet calculator

### ISSUE THREAD

**Issue by gormur** [DevToys-app/DevToys#184]
Vote on this issue by adding a 👍 reaction.
If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

Consider the subnet calculator at https://www.calculator.net/ip-subnet-calculator.html

It would be nice to have something similar implemented in this tool :)

**Comment by jachin84** [comment]
I was just about to File->New Project to create a subnet calculator similar to the one at https://www.certificationkits.com/cisco-ccna-subnet-calculator/. I immediately thought that DevToys would be a great home for this functionality. 

The way CertificationKits implement the CIDR Calcultor is excellent. I would love to see this functionality in DevToys.

I'd be willing to have a go at this with some help if anyone else is interested.

**Comment by jwfxpr** [comment]
#267 suggests some specific output formats for this feature.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
