### ISSUE TITLE
XML parser using XSLT

### ISSUE THREAD

**Issue by Andret2344** [DevToys-app/DevToys#196]
### Solution/Idea

I think it would be highly useful to allow "executing" XSLT providing matching XML to see the result in both HTML code and rendered (e.g. table).

### Alternatives

Some online stuff, but really hard to find good one, used to use "try it" editor on W3C [link](https://www.w3schools.com/xml/tryxslt.asp?xmlfile=cdcatalog&xsltfile=cdcatalog)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Parse XML using provided XSLT and show result code or error | Must |
| Render the result (usually the result is the HTML) | Should |
| Validate and clearly communicate the syntax error in both XSLT and XML | Could |
| Allows saving the result to XML/HTML file via button (instead of copying) | Could |

### DevToys Version

1.0.0.0; OS: Win11 v21H2, build 22000.438

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
