### ISSUE TITLE
CSS <> Lass <> Sass <> SCSS Converter

### ISSUE THREAD

**Issue by Andret2344** [DevToys-app/DevToys#197]
### Solution/Idea

The idea is to allow converting style sheets between the most widely known (Lass, Sass and SCSS) and pure CSS. Usually it's done at compile/interpret time via some watcher tool, but it's not good to do quick experiments.

### Alternatives

The only one is [Try It editor](https://www.w3schools.com/sass/showsass.php?filename=demo_sass_nest1) on W3C

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow change Less, Sass and SCSS to CSS | Must |
| Allow changing between Less, Sass and SCSS | Should |

### DevToys Version

Version: 1.0.0.0 | X64 | OS Version: 11.0.22000.438

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
