### ISSUE TITLE
Support blake3 hash

### ISSUE THREAD

**Issue by yujinlin0224** [DevToys-app/DevToys#204]
### What's the Problem?

Please support blake3 hash with 32 bytes and 64 bytes.

### Solution/Idea

This link might be helpful https://github.com/xoofx/Blake3.NET

### Alternatives

Currently I always use this website to generate blake3 hash https://connor4312.github.io/blake3/index.html

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by abc1236762** [comment]
Any plan about this one?

**Comment by yujinlin0224** [comment]
Why is not planned? Please give me a reason, thank you!

**Comment by veler** [comment]
Sorry, I thought I did but the message didn't go through.
Closing this issue as no upvote/traction on this issue after more than a year. In addition, this tool can be made as an extension using our SDK: https://devtoys.app/doc

**Comment by yujinlin0224** [comment]
thanks, i will try sdk when i have time.
