### ISSUE TITLE
Random String Generator

### ISSUE THREAD

**Issue by lkinsella** [DevToys-app/DevToys#210]
### What's the Problem?

It would be nice to have a random string generator, currently I use this a lot:

http://www.unit-conversion.info/texttools/random-string-generator/

However integrating it into this tool would be great.

### Solution/Idea

Under Generators new Random String section with Allowed Characters, Length and how many you want to generate. Maybe also option for casing.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Random String Generation | Must |
| Length | Must |
| Allowed Characters | Must |
| Number of Strings | Should |
| Character Casing | Could |

**Comment by jwfxpr** [comment]
If this were implemented in such a way as to be usable by other tools, it would be useful for populating fields for, eg, password salt as discussed at #179. Since we will generate random strings in other tools anyway, seems reasonable to make this a tool of its own.

**Comment by boast** [comment]
See also https://passwordsgenerator.net/ for a nice online implementation. It has a "do NOT send across the Internet" Option, however an integration into DevToys would be nice.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
