### ISSUE TITLE
JSON to JSON viewer

### ISSUE THREAD

**Issue by igor-h** [DevToys-app/DevToys#249]
### What's the Problem?

A internesting feature can be, have a JSON Viewer, like for example: 
[https://jsoneditoronline.org/](https://jsoneditoronline.org/)

so then we can viasualize the objects inside the json text, and open and close each element.
Have a search functionality...etc

This can be really interesting and useful for a lot of developers.

### Solution/Idea

Create a JSON Viewer, like for example: 
[https://jsoneditoronline.org/](https://jsoneditoronline.org/)

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

1.0.1.0

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
