### ISSUE TITLE
display-related units calculator/visualizer

### ISSUE THREAD

**Issue by expikr** [DevToys-app/DevToys#251]
* Would be great to have a centralized tool that helps UI Designers with quick visualization/calculation of screen-related units as well as screensizes and pixel density.
* can start with adding the easy absolute units like `vh`, `vw`, `px`, `em`, `pt`, `dp` etc. and incrementally add more. Paying attention to what the appropriate contextual fields should be each time a unit is added.
* End goal is to make the tool a centralized place that include every screen-related unit possible no matter how obscure they are (like the size of a StarCraft Brood War tile or cell, or console glyphs of vga text mode, etc)

**Comment by xeonmc** [comment]
This functionality, for example, would be great to have included in DevToys in some streamlined form:

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
