### ISSUE TITLE
Unable to install on Enterprise laptop

### ISSUE THREAD

**Issue by tmalaher-telus** [DevToys-app/DevToys#286]
### Description

I'm running Edition	Windows 10 Enterprise Version 20H2 OS build 19042.631
Our laptops have the Windows Store functionality disabled.
I have admin rights on the laptop, so I am able to install software (e.g. via .msi)

However, when I tried downloading DevToys.Startup_1.0.1.0_x86_x64_arm64.msixbundle (and the associated certificate) I was unable to install it.

The Windows says that the installer is a **Trusted App**, with *Publisher: etiennebaudoux*, so the certificate seems to be loaded OK.

But after saying "installing required packages...", it quickly gives the message:

```
DevToys installation failed
Reason:
App Installer failed to install package dependencies. Ask the developer for  package. 
```

Note the two spaces between "for" and "package" as if it is trying to insert the name of a package into that message.

Is there a known problem installing standalone? Or is there a missing dependency in the package, or something I need to install before installing DevToys?

### Steps To Reproduce

1. download DevToys.Startup_1.0.1.0_x86_x64_arm64.msixbundle
2. download DevToys.Startup_1.0.1.0_x86_x64_arm64.cer
3. install the .cer into the Trusted Root CA store
4. Double click on the .msixbundle
5. installation fails

### Expected behavior

Installation succeeds

### DevToys Version

 DevToys.Startup_1.0.1.0_x86_x64_arm64

### Relevant Assets/Logs

![Screenshot 2022-01-27 153126](https://user-images.githubusercontent.com/66433674/151454446-74653b95-8e25-40ef-91ef-709c83a34aff.png)

**Comment by veler** [comment]
Hello,
Thanks to @rlm96 , DevToys is now available on Chocolatey. Would you be able to give it a try and see if the app can be installed this way on your machine, please? :)

See: https://github.com/veler/DevToys#chocolatey

Thank you !

**Comment by Atrejoe** [comment]
Similar situation here.

On Chocolatey the missing dependency is more explicit:

```
Windows cannot install package 64360VelerSoftware.DevToys_1.0.2.0_x64__j80j2txgjg9dj because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.6" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 2.62108.18004.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.6" currently installed are: {}
```

**Comment by rlm96** [comment]
> Windows cannot install package 64360VelerSoftware.DevToys_1.0.2.0_x64__j80j2txgjg9dj because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.6"

Which OS version are you using (include build number, please)?

**Comment by rlm96** [comment]
Hmmm, can you check https://github.com/microsoft/winget-cli/issues/1779? 

> If you're installing App Installer via Add-AppxPackage in Windows PowerShell, you will first need to manually install Microsoft.VCLibs.140.00.UWPDesktop and Microsoft.UI.Xaml.2.6 before installing App Installer via Add-AppxPackage.

It seems that if we're using Add-AppxPackage (as we're using in the chocolateInstall.ps1) we may need to install previously some dependencies

**Comment by Atrejoe** [comment]
On my Windows 11 machine this worked just fine.(wihtout installing any dependencies)

On the dependencies: I don't get if these are machine-installable libraraies, or just project references:

https://nuget.info/packages/Microsoft.UI.Xaml/2.7.0
https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge

Should'nt these dependencies be resolved by the application installer or possibly deployed with the app?

**Comment by Renari** [comment]
Just ran into this issue myself on a fresh W11 install.

**Comment by jfheins** [comment]
I could install Devtoys now after collecting some dependencies
Microsoft.NET.Native.Framework.2.2.appx and
Microsoft.NET.Native.Runtime.2.2.appx
from here: https://github.com/fsclient/fsclient.github.io/tree/master/fs/FSClient.UWP/Dependencies/x64

And then the Redist from here:
https://github.com/M1k3G0/Win10_LTSC_VP9_Installer/blob/master/Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe.appx
And the Desktop version here: https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages

**Comment by johnmccrae** [comment]
Hi, new Lenovo similarly locked down by IT - Chocolatey fails with the missing XAML library. When I download the msixbundle I get a dependency installation failure

![image](https://user-images.githubusercontent.com/4855887/174463766-73ece2ac-f208-45ea-a2e1-06c40a1606ba.png)

**Comment by energister** [comment]
Just try [a workaround](http://woshub.com/how-to-download-appx-installation-file-for-any-windows-store-app/): use https://store.rg-adguard.net/ to download and install missing dependencies one by one

**Comment by tmalaher-telus** [comment]
@energister  I'm somewhat hesitant to download libraries/executables from random locations to an Enterprise laptop...
I trust @veler , so I'm willing to download an msi created by him, but adding things from third-party locations (either manually or via a package manager) seems dicey.

**Comment by energister** [comment]
@tmalaher-telus, I'm also avoiding to download something from unknown sites, so at the beginning I also excluded the option with the https://store.rg-adguard.net/. But later on I've noticed that the site just gives me links to the Microsoft's site. So it's safe to use it.

**Comment by david-evanochko** [comment]
@veler any updates regarding this bug? I'm hitting the road blocks outlined above with Chocolatey.

**Comment by Renari** [comment]
> @veler any updates regarding this bug? I'm hitting the road blocks outlined above with Chocolatey.

Read the above posts for how to manually install the missing dependencies.

**Comment by veler** [comment]
Hi,
This is now resolved with DevToys 2.0: https://devtoys.app/
Thanks!

**Comment by BranchBotanist** [comment]
@veler  I don't think it is

<img width="383" alt="image" src="https://github.com/user-attachments/assets/678449e9-8df0-4fee-80d6-d0cf5d3bb350">

**Comment by Atrejoe** [comment]
> @veler I don't think it is
I think this is likely to be a different issue. Original issue is about not being able to install prerequisites.
This appears to be about the application not being able to install at all because of protective measures in your/your company's smartscreen policies.

See also:
https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/available-settings

However, this is still an issue the DevToys devs may be able to address, just in a separate issue.
