### ISSUE TITLE
Show the currently selected category in the title bar

### ISSUE THREAD

**Issue by togetogejizou** [DevToys-app/DevToys#291]
### What's the Problem?

If you have multiple DevToys running, it's inconvenient to find the window you want because the title bars are all the same
![image1](https://user-images.githubusercontent.com/64200496/151529740-85338e58-1e91-478f-898a-4822c5c4ec6b.png)
.

### Solution/Idea

When multiple DevToys are running, for example, it is easier to select a target for window switching if the title bar displays something like "DevToys - Json Formatter".

### Alternatives

Just putting a sequential number at the end of the title bar in the order that DevToys was launched will improve things a bit.

**Comment by xeonmc** [comment]
or follow the convention of `<documentname> - <programname>` as seen in your taskbars' Office documents

**Comment by veler** [comment]
That's a great idea! :D I'm so much used at not seeing apps name in my task bar I didn't think about this. Thanks for this !

**Comment by PKU-Nekomaru** [comment]
Could I work on this? I'll follow the convention of <documentName> - <programName>.

**Comment by veler** [comment]
Re-open as we lost this when migrating to Blazor
