### ISSUE TITLE
SVG to XAML

### ISSUE THREAD

**Issue by veler** [DevToys-app/DevToys#30]
**Is your feature request related to a problem? Please describe.**
As a developer working with XAML, I find difficult to insert SVG into XAML file code.

**Describe the solution you'd like**
Add an SVG to XAML converter

**Additional context**
This is probably not a `mainstream` tool. This is probably relatively low priority. Also, there are some WPF/UWP libraries allowing to load SVG files straight into a XAML UI.

**Comment by theuserbl** [comment]
Seems there existing two project, which could be integrated in DevToys
https://github.com/BerndK/SvgToXaml
https://github.com/ElinamLLC/SvgXaml

Converting SVG to QML would also nice.

**Comment by veler** [comment]
I think these would be nice as extensions but not shipped by default with DevToys.
You can make extensions for DevToys by following this documentation: https://devtoys.app/doc/articles/introduction.html

I will close this issue as there's no plan to ship this by default in DevToys. Anyone interested by this feature, feel free to build and extension for it :)
