### ISSUE TITLE
Image Resize

### ISSUE THREAD

**Issue by EduardoDilena** [DevToys-app/DevToys#354]
### Solution/Idea

availability to adjust the size of the images

### Alternatives

availability to adjust the size of the images

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by KillyMXI** [comment]
PowerToys have this: https://docs.microsoft.com/en-us/windows/powertoys/image-resizer

**Comment by veler** [comment]
I believe every operating systems have equivalent. Considering low upvote and comment here, I will close this issue.
