### ISSUE TITLE
ASCII Table Generator

### ISSUE THREAD

**Issue by ahotko** [DevToys-app/DevToys#388]
### What's the Problem?

DevToys could include ASCII table generator.

### Solution/Idea

Similar solution is online, https://ozh.github.io/ascii-tables/

### Alternatives

https://ozh.github.io/ascii-tables/

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
