### ISSUE TITLE
.Msixbundle 安装失败

### ISSUE THREAD

**Issue by Lonely-lie** [DevToys-app/DevToys#420]
### Description

.Msixbundle安装失败，提示：
应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。
![image](https://user-images.githubusercontent.com/71426765/154874186-105f16eb-a055-45e2-af50-2e9fcaaca940.png)

### Steps To Reproduce

安装.Msixbundle 
![image](https://user-images.githubusercontent.com/71426765/154874196-ec5a02e6-953a-49d5-9741-cb29ca88ecf7.png)

### Expected behavior

安装成功

### DevToys Version

1.0.3.0

### Relevant Assets/Logs

nothing

**Comment by zzhzero** [comment]
+1

**Comment by Schaffer-W** [comment]
I also encountered such a problem, how did you solve it in the end.

**Comment by 19wym99** [comment]
Perhaps lacking relevant dependency libraries

**Comment by 19wym99** [comment]
Perhaps lacking relevant dependency libraries

**Comment by veler** [comment]
Hi,
This issue is solved in DevToys 2.0. See https://devtoys.app
