### ISSUE TITLE
PHP Unserialize

### ISSUE THREAD

**Issue by benjaminprojas** [DevToys-app/DevToys#424]
### What's the Problem?

We work with WordPress on a daily basis and a lot of database values are stored in a serialized format. it would be great to add a serialize converter/formatter. PHP's serialized code is completely unreadable and worse, almost impossible to edit.

### Solution/Idea

Add the ability to format/convert serialized data. That way we can visually see what is inside the block of code, make edits, and serialize it back.

### Alternatives

I usually spin up unserialize.com to do the dirty work. Not a fan of it though.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to unserialize PHP serialized code | Must |
| This proposal will allow end users to convert serialized code into JSON | Must |
| This proposal will allow end users to convert serialize code back into a PHP serialized block | Must |
| This proposal will allow developers to convert serialized code into other formats | Should |

### DevToys Version

0.0.7 (1)

**Comment by txemaquintero** [comment]
A VAR_DUMP() Formatter should be great too.

**Comment by veler** [comment]
Moved to backlog and closing to reduce amount of opened issues: https://github.com/users/veler/projects/1/views/1?pane=issue&itemId=23324678

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
