### ISSUE TITLE
Attempting to Install the MSIX Bundle offline fails

### ISSUE THREAD

**Issue by johncotter** [DevToys-app/DevToys#492]
### Description

I have a development machine that does not have direct internet access. Copied the msixbundle file over the the machine and when trying to install it fails with the following message.

"App installer failed to install package dependencies. ask the developer for Microsoft.vclibs.140.00 package"

### Steps To Reproduce

1. Turn off internet access
2. Run the .msixbundle
3. A dialog will present with an install button
4. Press install

### Expected behavior

The application to install successfully and run in an offline scenario.

### DevToys Version

1.0.6.0

### Relevant Assets/Logs

Error Msg: "App installer failed to install package dependencies. ask the developer for Microsoft.vclibs.140.00 package"

**Comment by Carterpersall** [comment]
It seems that you would also need to install the VCLibs package as well before it. It might be a good idea for someone to add a mention of that in the manual install directions. Or maybe add separate manual online and offline install directions.

**Comment by veler** [comment]
This is through in DevToys 2.0: https://devtoys.app/download
