### ISSUE TITLE
Hex editor

### ISSUE THREAD

**Issue by epeshk** [DevToys-app/DevToys#511]
### What's the Problem?

Feature request: Just a classic two-side hex editor, like HxD.

One side for bytes (as hex) and another for ASCII representation.

Should support copy/paste and open file, like Markdown Preview

### Solution/Idea

as stated above

### Alternatives

Use alternative tool, like HxD as mentioned above.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by themattman18** [comment]
I second this

**Comment by veler** [comment]
Moved to backlog: https://github.com/users/veler/projects/1/views/1?pane=issue&itemId=23324631

**Comment by bvtvusn** [comment]
Yes, would be great to have this. Maybe get some inspiratoren from https://hexed.it too?
I like the feature where you edit a lot of different data types

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
