### ISSUE TITLE
DevToys Portable Version

### ISSUE THREAD

**Issue by WhoIsConch** [DevToys-app/DevToys#514]
### What's the Problem?

For people that work with multiple different computers, a portable version of DevToys would come in handy.

### Solution/Idea

A portable version, one that's just an exe file with some other essential components. Some popular apps, such as [Git](https://github.com/git-for-windows/git/releases/download/v2.36.0.windows.1/PortableGit-2.36.0-64-bit.7z.exe) and [Visual Studio Code](https://code.visualstudio.com/docs/editor/portable) have portable versions, and they come in handy for people who work with multiple different computers.

### Alternatives

I have considered online versions for now, such as [SmallDevTools](https://smalldev.tools/]

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to load DevToys onto a portable storage media such as USB | Must |

**Comment by dongle-the-gadget** [comment]
Technically speaking, this is basically impossible without a complete rewrite.

**Comment by veler** [comment]
It might be possible with a WinUI 3 approach (not a 100% sure). Totally possible with a CLI version. Likely possible on MacOS and Linux too.

**Comment by veler** [comment]
Done in DevToys 2.0
