### ISSUE TITLE
Provide JS,CSS Minify 

### ISSUE THREAD

**Issue by AkbarAsghari** [DevToys-app/DevToys#556]
### What's the Problem?

I wanna minify js,css

### Solution/Idea

like online tools please provide js and css minifier

### Alternatives

like online tools please provide js and css minifier

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks

**Comment by AkbarAsghari** [comment]
thanks 
I agree with your opinion @veler
