### ISSUE TITLE
Create Wiki page for documentation

### ISSUE THREAD

**Issue by dovatti** [DevToys-app/DevToys#568]
### What's the Problem?

Documentation for repo's missing.

### Solution/Idea

Should we create `Wiki` page for this repository for create documentation for final user, developers and translators.

### Alternatives

Link for documentation on `devtoys.app/docs` or whatever.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi,
This is now resolved with DevToys 2.0: https://devtoys.app/
Thanks!
