### ISSUE TITLE
SQL Formatter PostgreSQL variables formatting error.

### ISSUE THREAD

**Issue by DimonSmart** [DevToys-app/DevToys#623]
### Description

@ symbol used as a variable in query formatted on a separate string
Example:
Input: SELECT * FROM SAMPLE LIMIT @LIMIT
Result: 
SELECT
  *
FROM
  SAMPLE
LIMIT
  **@
LIMIT**

Expected result:
SELECT
  *
FROM
  SAMPLE
LIMIT
  **@LIMIT**

### Expected behavior

Go to SQL format
Select PostgreSQL
Paste sample input

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

### Relevant Assets/Logs

no logs

**Comment by araujofrancisco** [comment]
Same issue is present in other Sql formatters, it seems to be working fine with Transact-SQL.
