### ISSUE TITLE
Binary Text Encoder/Decoder

### ISSUE THREAD

**Issue by otac0n** [DevToys-app/DevToys#628]
### What's the Problem?

Please support converting to/from Binary formatted text.

### Solution/Idea

For example, this is an online implementation.
https://www.rapidtables.com/convert/number/binary-to-ascii.html

### Alternatives

no alternative

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal must allow users to encode text as UTF8 or ASCII formatted binary. | Must |
| This proposal must allow users to decode UTF8 and ASCII formatted binary text. | Must |
| This proposal should allow users to choose an encoding. | Should |
| The app should automatically switch to binary decoder when binary formatted text is found on the clipboard. | Should |
| This proposal could auto-detect the character encoding when decoding. | Could |

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
