### ISSUE TITLE
Add Devtoys to winget

### ISSUE THREAD

**Issue by 01Vladimir10** [DevToys-app/DevToys#641]
### What's the Problem?

have you considered adding devtoys to the winget repository? I love the tool and I would love being able to install it by just running winget install devtoys from my terminal.

### Solution/Idea

https://docs.microsoft.com/en-us/windows/package-manager/package/repository

### Alternatives

.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Dreamescaper** [comment]
`winget install devtoys` works perfectly fine, it installs it via Microsoft Store integration.

**Comment by masterflitzer** [comment]
> `winget install devtoys` works perfectly fine, it installs it via Microsoft Store integration.

if chocolatey is supported it should also be supported by winget repo (not MS Store)

many people including me work on corporate devices/win server VMs where MS Store is disabled or not available

**Comment by veler** [comment]
Note to myself: check out work in progress here: https://github.com/microsoft/winget-pkgs/pull/43996

**Comment by AVTPJ** [comment]
Also the MS Store version which is installed via `winget` doesn't include version info, so I don't believe it shows up on `winget upgrade`

```bash
Name    Id           Version Source
-------------------------------------
DevToys 9PGCV4V3BK4W Unknown msstore
```

**Comment by SandeeepKiran** [comment]
Is there any update on this? It is currently 18th Sept 2023. More than a year later.

Unable to add DevToys to Winget scripts to auto-install when setting up new PCs and Desktops.
Even a simple Veler.DevToys will be well appreciated.

**Comment by veler** [comment]
> Is there any update on this? It is currently 18th Sept 2023. More than a year later.
> 
> 
> 
> Unable to add DevToys to Winget scripts to auto-install when setting up new PCs and Desktops.
> 
> Even a simple Veler.DevToys will be well appreciated.

Hi,
Still not on WinGet due to same limitation than mentioned previously. The good news though is that we're working on DevToys 2.0, which is a full rewrite and won't have the same limitation of UWP. We're hoping for a preview release early next year.

**Comment by veler** [comment]
It's coming :-) https://github.com/microsoft/winget-pkgs/pull/156567

**Comment by veler** [comment]
it is now available: https://devtoys.app/download

**Comment by glen-84** [comment]
I see this:

```
Name                                                               Id                            Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------------------
DevToys Preview version 2.0-preview.1                              DevToys-app.DevToys           2.0-preview.1 2.0.1         winget
```

After running `winget upgrade DevToys-app.DevToys` I seem to remain on the preview version, and `winget upgrade` shows the same as above.

IIRC, I also tried uninstalling first.

**Comment by masterflitzer** [comment]
> I see this:

yeah same, the version `2.0.1` in winget actually installs `2.0-preview.1` but is wrongly tagged as `2.0.1`, this results in upgrade loop

i probably commented on the wrong issue: https://github.com/microsoft/winget-pkgs/pull/156567#issuecomment-2166560844
