### ISSUE TITLE
Custom base in number converter

### ISSUE THREAD

**Issue by tomer002** [DevToys-app/DevToys#653]
### What's the Problem?

There are only options to convert the number to bases 2, 8, 10 and 16.

### Solution/Idea

Add an option to enter a custom radix from 1 (unary) to 36.
![Maybe it will look something like this](https://user-images.githubusercontent.com/78913951/188196876-d5197757-0b0f-4a27-aa40-c533ecc4f7da.png)

### Alternatives

If there will ever be an option to input numbers that aren't whole then the minimum value for the radix should be 2 instead of 1 because only whole numbers can be written in base 1.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Closing as no upvote/traction on this issue.
