### ISSUE TITLE
CSV Query

### ISSUE THREAD

**Issue by Manuel-Steinberg** [DevToys-app/DevToys#655]
### What's the Problem?

Working with CSV files is easy and fast, but bulk manipulations or more in depth queries can be tricky. Mostly I am using notepad++ with CsvQuery extension since it is way faster than Excel/Calc.

### Solution/Idea

1. Load a CSV file.
2. Set optional read params, e.g. seperator.
3. Write SQL statements against CSV file.
4. Export to another CSV file.

### Alternatives

[CsvQuery](https://github.com/jokedst/CsvQuery)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to set custom read param | Should |
| This proposal will allow end users to query a CSV with SQL | Must |
| This proposal will allow end users to export query result to CSV again  | Must |

**Comment by Manuel-Steinberg** [comment]
![image](https://user-images.githubusercontent.com/11491106/188304381-f159deee-8a55-4100-904d-2378c710eb6d.png)
Screenshot of how this looks like with notepad++ and CsvQuery extension.

**Comment by joshpinto6** [comment]
A feature like this would definitely be really great!

**Comment by Christian-Oleson** [comment]
Just as a general thought, this may be a more extensive feature to implement than some of the others since we have to write a way to query the data dynamically, since we don't have the model until we load the CSV and then have to allow folks to query on it (should use ANSI SQL).

**Comment by jamescurran** [comment]
I wonder if you could fork and adapt CsvQuery to work within DevToys.   
Alternately, we could reference the SQLite nuget package and build on that (having SQLite in the DevToys ecosystem may also be useful for future tools)

**Comment by bvtvusn** [comment]
I second this!

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
