### ISSUE TITLE
ALT codes tool

### ISSUE THREAD

**Issue by ghadzhigeorgiev** [DevToys-app/DevToys#705]
### What's the Problem?

Will be nice to have a reference to ALT codes and ability to use them inside DevToys and 4rd party apps.

### Solution/Idea

An info screen like the one at [ALT Code list](https://www.alt-codes.net/) and the ability to copy the symbol for use within DevToys or 3rd party app through Clipboard.

### Alternatives

[ALT Code list](https://www.alt-codes.net/)

### Priorities
Useful nice to have

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
