### ISSUE TITLE
SQL Formatter comma position option

### ISSUE THREAD

**Issue by MCrank** [DevToys-app/DevToys#712]
### What's the Problem?

As a developer/composer of some, mostly terrible, SQL queries I use the SQL formatter DevToy to make my queries more presentable or to make copy/pasted queries easier to read and understand.

### Solution/Idea

When building queries, I prefer to have the comma before the list of items as it makes it more efficient to comment out code and re-run for testing than to comment out a line and then go to the previous line and remove the comma as well. I think it would make a useful option to format the SQL statements both ways.

### Example of current functionality
```sql
SELECT
    f.title,
    f.replacement_cost,
    f.rental_rate,
    count(r.return_date) AS total_rentals
FROM
    film f
    INNER JOIN inventory inv ON inv.film_id = f.film_id
    INNER JOIN rental r ON r.inventory_id = inv.inventory_id
GROUP BY
    f.title,
    f.replacement_cost,
    f.rental_rate
```

### Example Proposed Fucntionality
```sql
SELECT 
    f.title
    , f.replacement_cost
    , f.rental_rate
    , count(r.return_date) AS total_rentals
FROM 
    film f
    INNER JOIN inventory inv ON inv.film_id = f.film_id
    INNER JOIN rental r ON r.inventory_id = inv.inventory_id
GROUP BY
    f.title
    , f.replacement_cost
    , f.rental_rate
```

### Alternatives

Here is an online formatter that provides this option.
https://sql-formatter-org.github.io/sql-formatter/

And an article online I found that talks about the option as well.

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by kandicst** [comment]
This seems pretty straightforward, so I'd like to take a whack at this.

Only thing, do we want commas to be vertically aligned with the first column like in your example, or for all columns to be aligned like in the sql formatter you linked?

I think that having all columns aligned looks better, however this is not possible when tab is used for indentation (as we can't go back two characters to put a comma and space).

**Comment by MCrank** [comment]
Hmm. I agree with you that it looks better with the names aligned but I leave that up to you on implementing it since you are the one taking the time to sling the code.  The end goal is to have the commas at the beginning and if that gets kinda wonkey because of tabs vs spaces I'd be happy with either way.

And thank you for picking this up.

**Comment by MCrank** [comment]
Woohoo! Thanks folks

**Comment by veler** [comment]
Big thanks to @akarboush who made an amazing PR!
