### ISSUE TITLE
Use  pngquant-bin to compress png

### ISSUE THREAD

**Issue by jesus-mg-ios** [DevToys-app/DevToys#732]
### What's the Problem?

I realised that png usually has a low compression. Is it possible to use pngquant-bin for it?

Thanks in advance

### Solution/Idea

Look for other tools like pngquant-bin to use it.

### Alternatives

Look for other tools like pngquant-bin to use it.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi,
I didn't know about this one! Looks promising. Thanks for sharing!

Note to myself: check out https://pngquant.org/, there is a command line tool for Windows and Mac.

**Comment by veler** [comment]
Hi,
This is now resolved with DevToys 2.0: https://devtoys.app/
Thanks!
