### ISSUE TITLE
Stand-Alone Installer for Windows without Powershell

### ISSUE THREAD

**Issue by LVBernardes** [DevToys-app/DevToys#741]
### What's the Problem?

Hello, PowerToys is a powerful tool to use on a daily basis and I would like to bring it to my job however due to security policies we are not allowed to use Powershell on employees machines, so the standard installation using the AppxBundle does not work properly.
And usually we can install softwares on our machines via Cyberark EPM Agent or Microsoft SCCM.

### Solution/Idea

Develop a standalone installer, e.g. an MSI package, with all its dependencies.
This way we can download directly and install with no worries about security blocks or anything else.

### Alternatives

A Appx package but with all the dependencies included in a way that we can just extract and execute without further use of Powershell.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers in organizations with restricted environments to use the PowerToys | Must |

### DevToys Version

v1.0.10.0

**Comment by veler** [comment]
Hi,
This is now resolved with DevToys 2.0: https://devtoys.app/
Thanks!
