### ISSUE TITLE
1903/1909 support

### ISSUE THREAD

**Issue by logoffon** [DevToys-app/DevToys#751]
### Discussed in https://github.com/veler/DevToys/discussions/714

<div type='discussions-op-text'>

<sup>Originally posted by **logoffon** November 21, 2022</sup>
It seems that the [readme](https://github.com/veler/DevToys/blob/main/README.md) has an incorrect listing for the minimum version of Windows required to run DevToys.
The readme lists it as v1903 or later, but both Microsoft Store and the msixbundle itself requires v2004 (aka 20H1/build 19041) or later:
![image](https://user-images.githubusercontent.com/7828523/203020079-6a23934a-c0f4-4305-b009-4e4fd1692e8d.png)
![image](https://user-images.githubusercontent.com/7828523/203020121-841b0a6c-8850-49d8-b55f-d4c0fd38d045.png)
`App installation failed with error message: Windows cannot install package 64360VelerSoftware.DevToys_1.0.10.0_x64__j80j2txgjg9dj because this package is not compatible with the device. The package requires OS version 10.0.19041.0 or higher on the Windows.Desktop device family. The device is currently running OS version 10.0.18363.418. (0x80073cfd)`
Per the log, I'm currently running v1909 (build 18363) and due to specific requirements of a software I use it's not possible for me to upgrade to more recent versions. Would you consider providing support for this app to run on 1903 and 1909?</div>

**Comment by veler** [comment]
Fixed in 2.0 (releasing in a few months)
