### ISSUE TITLE
Messy code recovery

### ISSUE THREAD

**Issue by BobYue-01** [DevToys-app/DevToys#753]
### What's the Problem?

Most programmers of CJK languages often encounter garbled text due to encoding errors.

They need to try to convert to other encodings and find the correct one.

### Solution/Idea

Input garbled text; output texts converted to other encodings.

Just like what these tools do:
[Recover garbled text online](https://wrtools.top/coderepair.php)
[as_messycoderecover](https://github.com/Medicean/as_messycoderecover)

Common encodings:
- UTF-8
- UTF-16
- GBK
- ISO-8859-1
- WINDOWS-1252
- BIG5

### Alternatives

I don't think I need to put anything in this field. Maybe I misunderstood its meaning.

The feature requested and alternative tools are above.

### DevToys Version

版本 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by veler** [comment]
Closing as no upvote/traction on this issue.
