### ISSUE TITLE
SQL Formatter improvement suggestion

### ISSUE THREAD

**Issue by Kjelli** [DevToys-app/DevToys#754]
### What's the Problem?

"Problem". Well, I'd like the word `apply` to be upper-cased to be consistent with other keywords, when formatting SQL. :neckbeard: 😄 

### Solution/Idea

Uppercase it 😄 

### Alternatives

Uppercasing it myself! But this is 2023, and I don't think it's an approperiate use of my time. /s 😏 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to uppercase the word 'apply' | Could be nice! |

### Comments

It really isn't a big deal, I'm just letting you guys know about it! 😄

**Comment by veler** [comment]
Is `apply` a valid keyword in SQL? Sorry to ask, SQL newbie here :D
