### ISSUE TITLE
DevToys installation failed in System context

### ISSUE THREAD

**Issue by Bala826** [DevToys-app/DevToys#767]
My Windows OS version is 10.0.19042 Enterprise edition.

I tried install the DevToys but it failed in system context. Could you please provide the solution here? See the error below for reference. I given the full permission but still its failing.

PS C:\local\DevToys> **add-AppxPackage -Path "C:\local\DevToys\64360VelerSoftware.DevToys_1.0.10.0_neutral_._j80j2txgjg9dj.msixbundle" -Verbose**
VERBOSE: Performing the operation "Deploy package" on target "C:\local\DevToys\64360VelerSoftware.DevToys_1.0.10.0_neutral_._j80j2txgjg9dj.msixbundle".
add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor. (Exception from HRESULT: 0x80073CF9)
Deployment Add operation rejected on package 64360VelerSoftware.DevToys_1.0.10.0_neutral_~_j80j2txgjg9dj from: 64360VelerSoftware.DevToys_1.0.10.0_neutral_._j80j2txgjg9dj.msixbundle install request because the Local System account is
not allowed to perform this operation.
NOTE: For additional information, look for [ActivityId] 061b40c5-5182-0006-ac34-29068251d901 in the Event Log or use the command line Get-AppPackageLog -ActivityID 061b40c5-5182-0006-ac34-29068251d901
At line:1 char:1
+ add-AppxPackage -Path "C:\local\DevToys\64360VelerSoftware.DevToys_1. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\local\DevToy...g9dj.msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by veler** [comment]
Hi,
Can you try with admin rights?

**Comment by veler** [comment]
I see. As far as I know, admin rights are unfortunately required to install an MSIXBundle on Windows.
I don't have a workaround to offer for now. That said, we're currently working on DevToys 2.0, which will have the option to be portable. This could be an option if you can wait this summer or this fall.

**Comment by Bala826** [comment]
Hi, I wanted to check if there are any updates on the release of DevToys 2.0 or a revised estimated timeframe for its availability?

**Comment by veler** [comment]
Hi,
We did a lot of progress but obviously we are far behind what we were expecting. The good news is that we're at the finishing steps. It remains us only 1 tool to port from 1.0 to 2.0. Following this, we will need to do some touch up work, and finally release a preview. We're hoping for a preview in April/May.
There will be a portable version, which won't require the Microsoft Store, so your issue should be solved.
Thanks for your patience!

**Comment by veler** [comment]
I believe this issue is fixed with DevToys 2.0 now: https://devtoys.app/download
