### ISSUE TITLE
Use single diff editor for text comparer

### ISSUE THREAD

**Issue by BreeceW** [DevToys-app/DevToys#781]
### What improvement do you think would an existing feature or tool in DevToys?

The boxes in the text comparer tool are redundant and can be simplified to one box.

### Solution/Idea

Instead of the current layout, Old text, New text, and Difference, the Old text and New text boxes could be removed and the Difference box could be made editable.

### Comments

This can be accomplished by setting `originalEditable: true` in `createDiffEditor`. I don’t know how/if this would work for inline mode. If it does not, the Old text and New text boxes could show only for inline mode. But the space savings and usability improvements would be worth it in for side-by-side mode.

**Comment by BreeceW** [comment]
![DevToys text compare tool with one big side by side editor. Each side is labeled “Can edit here”](https://user-images.githubusercontent.com/18747724/229328141-91bc23f4-e659-480a-9d2c-d1a857b4265a.png)
Here’s a rough mockup.

**Comment by veler** [comment]
That's something we could do, but I'm wondering how this would work with the Inline mode, since the editor would not be splitted vertically.

![image](https://user-images.githubusercontent.com/3747805/229329610-b56cccdc-7ae1-49f4-b526-e3fa4e1ac444.png)
