### ISSUE TITLE
Running extra instances when Windows lock-unlock

### ISSUE THREAD

**Issue by mikhailpasukhin** [DevToys-app/DevToys#810]
### Current behavior

If I have running DevToys, it runs up to 3 extra instances when I lock-unlock Windows and original instance hangs (doesn't react on any clicks)

### How to reproduce it (as minimally and precisely as possible)

1. Run DevToys
2. Lock Windows (Win + L)
3. Unlock Windows (by password or by cam)

### Expected behavior

DevToys instances number doesn't change and original instance doesn't hang

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Версия 1.0.11.0 | X64 | RELEASE | 2b57a920 | 2b57a920

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/11462550/logs.txt)

**Comment by veler** [comment]
Hi,
Thanks for sharing this feedback. I unfortunately do not reproduce this issue and the logs aren't helpful at the moment.
When the issue reproduces for you:
1. Does a particular active is displayed in DevToys (like Base64 encoder/decoder or JSON Formatter) ?
2. Is Smart Detection enabled? If yes, is there anything in the clipboard? If yes, is it any particular kind of data that could interest DevToys, such as an XML, JSON, file, image, Base64 text...etc ?
3. Does it reproduce constantly in your configuration?
Thanks

**Comment by vanekvac** [comment]
Hello,
I have same behaviar as @mikhailpasukhin on version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

First try to reproduce:
- My clipboard have this value `<GlobalMapModal />`
- I have active "XML" and "Validator XML"
- I have active "Smart detection"
- After lock and unlock new window is spawned

Second try:
- empty clipboard
- no active tools
- same behavior - after unlock new window is spawned

**Comment by veler** [comment]
Fixed in DevToys 2.0 (to be released in a few months)
