### ISSUE TITLE
HTML Beautify/Minify

### ISSUE THREAD

**Issue by zuluranger** [DevToys-app/DevToys#861]
### What feature or new tool do you think should be added to DevToys?

Spruce up messy, minified HTML code or boost your website's performance by minifying the HTML code.

### Why do you think this is needed?

Minifying HTML code involves removing unnecessary characters such as whitespaces, line breaks, and comments. This reduces the overall file size and improves the website's loading speed.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
