### ISSUE TITLE
HAR analyzer

### ISSUE THREAD

**Issue by zkelo** [DevToys-app/DevToys#869]
### What feature or new tool do you think should be added to DevToys?

I suggest to add HAR analyzer tool

https://toolbox.googleapps.com/apps/har_analyzer

### Why do you think this is needed?

Because it's very useful tool for developers who need to debug network requests

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
