### ISSUE TITLE
Swagger/OpenAPI UI

### ISSUE THREAD

**Issue by Regenhardt** [DevToys-app/DevToys#893]
### What feature or new tool do you think should be added to DevToys?

A Swagger/OpenAPI UI or playground like Swashbuckle, but taking a link to either a local file or a openapi.json on the web.

### Why do you think this is needed?

Sometime I want to test a webservice that provides an openapi spec, but not an integrated swagger UI. Can't use an arbitrary swagger UI either because CORS might block the swagger UI from loading the openapi spec of another webserviec.

**Comment by maftieu** [comment]
An OpenAPI validator would also be great.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
