### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by wutipong** [DevToys-app/DevToys#898]
### What feature or new tool do you think should be added to DevToys?

A simple random number generator that can generates a list of number within the given range. 

### Why do you think this is needed?

When writing unit test, sometimes there are needs to test against a group of input number. Using random numbers can be a good starting point.

Also when using some tools that require a group of seeding numbers (like... Automatic1111/stable-diffusion-webui), creating a list can be annoying. 

### Solution/Idea

Create a new generator similar to Password Generator or UUID.

**Comment by wutipong** [comment]
![image](https://github.com/veler/DevToys/assets/3213191/1935c8af-b9f5-4595-a883-950cf7727c53)

Here's an idea of what it would look like.  I quickly whip some code changes and got it somewhat working (with quite a few problems).

**Comment by notcooler** [comment]
I am thinking of creating this one, are you guys still interested in this one?

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. Can be made as an extension if anyone wants to try our SDK: https://devtoys.app/doc
