### ISSUE TITLE
Protobuf support

### ISSUE THREAD

**Issue by darjanbogdan** [DevToys-app/DevToys#928]
### What feature or new tool do you think should be added to DevToys?

A Protobuf tool that would enable easy de/serialization based on .proto contracts.

### Why do you think this is needed?

DevToys app is the best application to reduce the need for online tooling which can be forbidden to use in some cases (i.e. enterprise businesses).

While there are plenty of tools that handle Protobuf, DevToys would complement its JSON/XML capabilities to support the broadly used binary format.

### Solution/Idea

I'm not familiar with Desktop development concepts. But I think having a simple page like "https://www.protobufpal.com/"  would be more than enough for a starter.

### Comments

Thanks a lot for all your dedication so far! :)

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
