### ISSUE TITLE
Convert certificates

### ISSUE THREAD

**Issue by sweco-sepeec** [DevToys-app/DevToys#931]
### What feature or new tool do you think should be added to DevToys?

Ability to convert certificates between pfx and crt/key.

### Why do you think this is needed?

Converting certificates is a quite common task when working in both windows and linux environments.

**Comment by veler** [comment]
Hi,
I admit I'm quite unfamiliar with how certificate work as my day-to-day work doesn't require me to work with them. Aren't PFX and CRT files the same thing, but with a different extension? Could you please clarify me how they're generally converted from a type to another?

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
