### ISSUE TITLE
Custom CRC generator 

### ISSUE THREAD

**Issue by cwichel** [DevToys-app/DevToys#947]
### What feature or new tool do you think should be added to DevToys?

Would be neat to have a generator for a fully customizable CRC calculator in which you can select: 
- Bit size: 3, 5, 8, 16, 32
- Parameters: poly, init, reversed input/output, xor input/output 

This could've an option to import/export custom CRC configurations, for example, to create a variant of a "default" CRC-8, such as CRC-8/DARC 

### Why do you think this is needed?

It would be very useful to validate CRC implementation/computation/parameters when developing 

### Solution/Idea

Something similar to: [CRC calc](https://crccalc.com/)

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
