### ISSUE TITLE
Hungarian notation

### ISSUE THREAD

**Issue by KeSaite** [DevToys-app/DevToys#964]
### What feature or new tool do you think should be added to DevToys?

Regarding the Text Case Converter and inspector, it is possible to support the Hungarian notation.I need this feature.

### Why do you think this is needed?

I became accustomed to using Hungarian notation, and when I heard about this program, I tried all the features in great detail, but the one I was most looking forward to was this one.

### Comments

<img width="765" alt="image" src="https://github.com/veler/DevToys/assets/13944595/df55170c-6891-4e44-bbcb-8666467d90ba">

**Comment by veler** [comment]
Hi,

I'm not sure to follow what is the proposal here. Are you suggesting having a form that would allow the customer to automatically add a prefix name to any sort of text?

**Comment by veler** [comment]
Closing as no upvote/traction on this issue. This tool be made as an extension using our SDK: https://devtoys.app/doc
