### ISSUE TITLE
JSON Diff

### ISSUE THREAD

**Issue by json-ast** [DevToys-app/DevToys#967]
### What feature or new tool do you think should be added to DevToys?

I think a simple JSON difference tool would be nice. Something like [json diff](https://www.jsondiff.com)

### Why do you think this is needed?

My team and I use DevToys but we found it only has text comparison, so something like that for JSON would be nice.

### Solution/Idea

I think this design would be nice to have.

![image](https://github.com/veler/DevToys/assets/134556518/5ec7ddad-56aa-49e9-8d1d-e08e74494fec)

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
