### ISSUE TITLE
HTML Formatter that supports Confluence tags

### ISSUE THREAD

**Issue by d4nielix** [DevToys-app/DevToys#973]
### What feature or new tool do you think should be added to DevToys?

Hi. I love using DevToys, it helps me a lot in my everyday basis. There is only one case, where this tool fails. It is XML Formatter. I am working with source code of Confluence pages. Confluence has its own html tags, like <ac:rich-text-body> or <ac:parameter>.

When I paste HTML code from Confluence into XML formatter I get errors. For example:
`<p><ac:structured-macro ac:name="my-test-macro" ac:schema-version="1"><ac:parameter ac:name="parameter">true</ac:parameter></ac:structured-macro></p>` I get an error:
`'ac' is an undeclared prefix. Line 1, position 5.`

### Why do you think this is needed?

Using already existing XML Formatter results in errors

### Solution/Idea

I believe that there could be a flag that allows to skip checking prefixes, or tag names, so it will just format everything if the order of tags is met. In this way, we could format everything. Even something like this:

`<tag1:tag1><tag2:tag2><tag3:tag3></tag3:tag3></tag2:tag2></tag1:tag1>`

**Comment by veler** [comment]
Duplicate with #176
