### ISSUE TITLE
New Converters Idea -> JSON <> MARKDOWN

### ISSUE THREAD

**Issue by DeonPieterse** [DevToys-app/DevToys#987]
### What improvement do you think would an existing feature or tool in DevToys?

I think it would be cool to have a converter like you have `JSON <> YAML` but for `JSON <> MARKDOWN`.

The reason I think this is a good feature is that sometimes we want to easily document, for instance our configuration files and the values inside of it.

Now if I could easily convert my `JSON` config file to a `MARKDOWN` table for instance, that would be convenient!

Example of where it could go:
![image](https://github.com/veler/DevToys/assets/27224022/f7ea7806-ca4c-46f8-94da-2b50390dba7f)

### Solution/Idea

I think it would be cool to have a converter like you have `JSON <> YAML` but for `JSON <> MARKDOWN`.

The reason I think this is a good feature is that sometimes we want to easily document, for instance our configuration files and the values inside of it.

Now if I could easily convert my `JSON` config file to a `MARKDOWN` table for instance, that would be convenient!

Example of where it could go:
![image](https://github.com/veler/DevToys/assets/27224022/f7ea7806-ca4c-46f8-94da-2b50390dba7f)

**Comment by veler** [comment]
We added a JSON Array > Table in DevToys 2.0. It allows to export the table to CSV format. Perhaps we could add Markdown

![image](https://github.com/veler/DevToys/assets/3747805/67f0418b-ade0-48c1-b194-15649710b4ff)

**Comment by parthpatel16** [comment]
@veler Can I work on this if it's not assigned to anyone?

**Comment by veler** [comment]
Please do! 😁 Thanks for suggesting your help!
Make sure to work from 'dev/2.0' branch, as DevToys 2.0 implementation is completely different than 1.0 (main branch).

**Comment by ppatel1604** [comment]
@veler Can I work on this if it's not assigned to anyone?

**Comment by ppatel1604** [comment]
Thanks @veler Happy to help and learn more about it 😄

**Comment by veler** [comment]
Thanks! Here is an entry point : 

https://github.com/veler/DevToys/blob/dev/2.0/src/app/dev/DevToys.Tools/Tools/Converters/JsonTable/JsonTableConverterGuiTool.cs

Make sure to read the CONTRIBUTING  file in this branch to setup your environment. We're also happy to listen to how hard it is to work on the repository.

**Comment by veler** [comment]
Hi,
This is a good idea for an [extension](https://devtoys.app/doc), but I don't think it fits DevToys' default tools.
Thanks
